// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	"journal/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/news",
				Handler: ListNewsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/news/:id",
				Handler: GetNewsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/papers",
				Handler: ListPapersHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/papers/:id",
				Handler: GetPaperHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/papers/search",
				Handler: SearchPapersHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/login",
				Handler: UserLoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/register",
				Handler: UserRegisterHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/papers/:id/rate",
				Handler: RatePaperHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/papers/:id/ratings",
				Handler: GetPaperRatingsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/papers/submit",
				Handler: SubmitPaperHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/user/info",
				Handler: GetUserInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/user/papers",
				Handler: UserPapersHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/user/profile",
				Handler: UpdateProfileHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/user/ratings",
				Handler: UserRatingsHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/news",
				Handler: AdminCreateNewsHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/papers/:id/zone",
				Handler: AdminUpdateZoneHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1/admin"),
	)
}
