// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: proto/rating.proto

package rating

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Rating_RatePaper_FullMethodName       = "/rating.Rating/RatePaper"
	Rating_GetPaperRatings_FullMethodName = "/rating.Rating/GetPaperRatings"
	Rating_GetUserRatings_FullMethodName  = "/rating.Rating/GetUserRatings"
)

// RatingClient is the client API for Rating service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RatingClient interface {
	RatePaper(ctx context.Context, in *RatePaperReq, opts ...grpc.CallOption) (*RateResp, error)
	GetPaperRatings(ctx context.Context, in *PaperRatingsReq, opts ...grpc.CallOption) (*PaperRatingsResp, error)
	GetUserRatings(ctx context.Context, in *UserRatingsReq, opts ...grpc.CallOption) (*UserRatingsResp, error)
}

type ratingClient struct {
	cc grpc.ClientConnInterface
}

func NewRatingClient(cc grpc.ClientConnInterface) RatingClient {
	return &ratingClient{cc}
}

func (c *ratingClient) RatePaper(ctx context.Context, in *RatePaperReq, opts ...grpc.CallOption) (*RateResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RateResp)
	err := c.cc.Invoke(ctx, Rating_RatePaper_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ratingClient) GetPaperRatings(ctx context.Context, in *PaperRatingsReq, opts ...grpc.CallOption) (*PaperRatingsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PaperRatingsResp)
	err := c.cc.Invoke(ctx, Rating_GetPaperRatings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ratingClient) GetUserRatings(ctx context.Context, in *UserRatingsReq, opts ...grpc.CallOption) (*UserRatingsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserRatingsResp)
	err := c.cc.Invoke(ctx, Rating_GetUserRatings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RatingServer is the server API for Rating service.
// All implementations must embed UnimplementedRatingServer
// for forward compatibility.
type RatingServer interface {
	RatePaper(context.Context, *RatePaperReq) (*RateResp, error)
	GetPaperRatings(context.Context, *PaperRatingsReq) (*PaperRatingsResp, error)
	GetUserRatings(context.Context, *UserRatingsReq) (*UserRatingsResp, error)
	mustEmbedUnimplementedRatingServer()
}

// UnimplementedRatingServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRatingServer struct{}

func (UnimplementedRatingServer) RatePaper(context.Context, *RatePaperReq) (*RateResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RatePaper not implemented")
}
func (UnimplementedRatingServer) GetPaperRatings(context.Context, *PaperRatingsReq) (*PaperRatingsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPaperRatings not implemented")
}
func (UnimplementedRatingServer) GetUserRatings(context.Context, *UserRatingsReq) (*UserRatingsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserRatings not implemented")
}
func (UnimplementedRatingServer) mustEmbedUnimplementedRatingServer() {}
func (UnimplementedRatingServer) testEmbeddedByValue()                {}

// UnsafeRatingServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RatingServer will
// result in compilation errors.
type UnsafeRatingServer interface {
	mustEmbedUnimplementedRatingServer()
}

func RegisterRatingServer(s grpc.ServiceRegistrar, srv RatingServer) {
	// If the following call pancis, it indicates UnimplementedRatingServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Rating_ServiceDesc, srv)
}

func _Rating_RatePaper_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RatePaperReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RatingServer).RatePaper(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Rating_RatePaper_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RatingServer).RatePaper(ctx, req.(*RatePaperReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rating_GetPaperRatings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PaperRatingsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RatingServer).GetPaperRatings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Rating_GetPaperRatings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RatingServer).GetPaperRatings(ctx, req.(*PaperRatingsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rating_GetUserRatings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRatingsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RatingServer).GetUserRatings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Rating_GetUserRatings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RatingServer).GetUserRatings(ctx, req.(*UserRatingsReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Rating_ServiceDesc is the grpc.ServiceDesc for Rating service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Rating_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rating.Rating",
	HandlerType: (*RatingServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RatePaper",
			Handler:    _Rating_RatePaper_Handler,
		},
		{
			MethodName: "GetPaperRatings",
			Handler:    _Rating_GetPaperRatings_Handler,
		},
		{
			MethodName: "GetUserRatings",
			Handler:    _Rating_GetUserRatings_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/rating.proto",
}
