// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: proto/rating.proto

package rating

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RatePaperReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaperId       int64                  `protobuf:"varint,1,opt,name=paper_id,json=paperId,proto3" json:"paper_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Score         int32                  `protobuf:"varint,3,opt,name=score,proto3" json:"score,omitempty"` // 1-10
	Comment       string                 `protobuf:"bytes,4,opt,name=comment,proto3" json:"comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RatePaperReq) Reset() {
	*x = RatePaperReq{}
	mi := &file_proto_rating_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RatePaperReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RatePaperReq) ProtoMessage() {}

func (x *RatePaperReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rating_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RatePaperReq.ProtoReflect.Descriptor instead.
func (*RatePaperReq) Descriptor() ([]byte, []int) {
	return file_proto_rating_proto_rawDescGZIP(), []int{0}
}

func (x *RatePaperReq) GetPaperId() int64 {
	if x != nil {
		return x.PaperId
	}
	return 0
}

func (x *RatePaperReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *RatePaperReq) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *RatePaperReq) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

type RatingItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	PaperId       int64                  `protobuf:"varint,2,opt,name=paper_id,json=paperId,proto3" json:"paper_id,omitempty"`
	UserId        int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	Nickname      string                 `protobuf:"bytes,5,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Score         int32                  `protobuf:"varint,6,opt,name=score,proto3" json:"score,omitempty"`
	Comment       string                 `protobuf:"bytes,7,opt,name=comment,proto3" json:"comment,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RatingItem) Reset() {
	*x = RatingItem{}
	mi := &file_proto_rating_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RatingItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RatingItem) ProtoMessage() {}

func (x *RatingItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rating_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RatingItem.ProtoReflect.Descriptor instead.
func (*RatingItem) Descriptor() ([]byte, []int) {
	return file_proto_rating_proto_rawDescGZIP(), []int{1}
}

func (x *RatingItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RatingItem) GetPaperId() int64 {
	if x != nil {
		return x.PaperId
	}
	return 0
}

func (x *RatingItem) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *RatingItem) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RatingItem) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *RatingItem) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *RatingItem) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *RatingItem) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type PaperRatingsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaperId       int64                  `protobuf:"varint,1,opt,name=paper_id,json=paperId,proto3" json:"paper_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaperRatingsReq) Reset() {
	*x = PaperRatingsReq{}
	mi := &file_proto_rating_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaperRatingsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaperRatingsReq) ProtoMessage() {}

func (x *PaperRatingsReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rating_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaperRatingsReq.ProtoReflect.Descriptor instead.
func (*PaperRatingsReq) Descriptor() ([]byte, []int) {
	return file_proto_rating_proto_rawDescGZIP(), []int{2}
}

func (x *PaperRatingsReq) GetPaperId() int64 {
	if x != nil {
		return x.PaperId
	}
	return 0
}

func (x *PaperRatingsReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *PaperRatingsReq) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type PaperRatingsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*RatingItem          `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	AvgScore      float64                `protobuf:"fixed64,3,opt,name=avg_score,json=avgScore,proto3" json:"avg_score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaperRatingsResp) Reset() {
	*x = PaperRatingsResp{}
	mi := &file_proto_rating_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaperRatingsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaperRatingsResp) ProtoMessage() {}

func (x *PaperRatingsResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rating_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaperRatingsResp.ProtoReflect.Descriptor instead.
func (*PaperRatingsResp) Descriptor() ([]byte, []int) {
	return file_proto_rating_proto_rawDescGZIP(), []int{3}
}

func (x *PaperRatingsResp) GetItems() []*RatingItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *PaperRatingsResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *PaperRatingsResp) GetAvgScore() float64 {
	if x != nil {
		return x.AvgScore
	}
	return 0
}

type UserRatingsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserRatingsReq) Reset() {
	*x = UserRatingsReq{}
	mi := &file_proto_rating_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRatingsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRatingsReq) ProtoMessage() {}

func (x *UserRatingsReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rating_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRatingsReq.ProtoReflect.Descriptor instead.
func (*UserRatingsReq) Descriptor() ([]byte, []int) {
	return file_proto_rating_proto_rawDescGZIP(), []int{4}
}

func (x *UserRatingsReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserRatingsReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *UserRatingsReq) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type UserRatingsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*RatingItem          `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserRatingsResp) Reset() {
	*x = UserRatingsResp{}
	mi := &file_proto_rating_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRatingsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRatingsResp) ProtoMessage() {}

func (x *UserRatingsResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rating_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRatingsResp.ProtoReflect.Descriptor instead.
func (*UserRatingsResp) Descriptor() ([]byte, []int) {
	return file_proto_rating_proto_rawDescGZIP(), []int{5}
}

func (x *UserRatingsResp) GetItems() []*RatingItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *UserRatingsResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type RateResp struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Success        bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message        string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	NewAvgRating   float64                `protobuf:"fixed64,3,opt,name=new_avg_rating,json=newAvgRating,proto3" json:"new_avg_rating,omitempty"`
	NewRatingCount int32                  `protobuf:"varint,4,opt,name=new_rating_count,json=newRatingCount,proto3" json:"new_rating_count,omitempty"`
	NewShitScore   float64                `protobuf:"fixed64,5,opt,name=new_shit_score,json=newShitScore,proto3" json:"new_shit_score,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RateResp) Reset() {
	*x = RateResp{}
	mi := &file_proto_rating_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RateResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RateResp) ProtoMessage() {}

func (x *RateResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rating_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RateResp.ProtoReflect.Descriptor instead.
func (*RateResp) Descriptor() ([]byte, []int) {
	return file_proto_rating_proto_rawDescGZIP(), []int{6}
}

func (x *RateResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RateResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RateResp) GetNewAvgRating() float64 {
	if x != nil {
		return x.NewAvgRating
	}
	return 0
}

func (x *RateResp) GetNewRatingCount() int32 {
	if x != nil {
		return x.NewRatingCount
	}
	return 0
}

func (x *RateResp) GetNewShitScore() float64 {
	if x != nil {
		return x.NewShitScore
	}
	return 0
}

var File_proto_rating_proto protoreflect.FileDescriptor

const file_proto_rating_proto_rawDesc = "" +
	"\n" +
	"\x12proto/rating.proto\x12\x06rating\"r\n" +
	"\fRatePaperReq\x12\x19\n" +
	"\bpaper_id\x18\x01 \x01(\x03R\apaperId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x14\n" +
	"\x05score\x18\x03 \x01(\x05R\x05score\x12\x18\n" +
	"\acomment\x18\x04 \x01(\tR\acomment\"\xd7\x01\n" +
	"\n" +
	"RatingItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x19\n" +
	"\bpaper_id\x18\x02 \x01(\x03R\apaperId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\x12\x1a\n" +
	"\busername\x18\x04 \x01(\tR\busername\x12\x1a\n" +
	"\bnickname\x18\x05 \x01(\tR\bnickname\x12\x14\n" +
	"\x05score\x18\x06 \x01(\x05R\x05score\x12\x18\n" +
	"\acomment\x18\a \x01(\tR\acomment\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\x03R\tcreatedAt\"]\n" +
	"\x0fPaperRatingsReq\x12\x19\n" +
	"\bpaper_id\x18\x01 \x01(\x03R\apaperId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"o\n" +
	"\x10PaperRatingsResp\x12(\n" +
	"\x05items\x18\x01 \x03(\v2\x12.rating.RatingItemR\x05items\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\x12\x1b\n" +
	"\tavg_score\x18\x03 \x01(\x01R\bavgScore\"Z\n" +
	"\x0eUserRatingsReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"Q\n" +
	"\x0fUserRatingsResp\x12(\n" +
	"\x05items\x18\x01 \x03(\v2\x12.rating.RatingItemR\x05items\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"\xb4\x01\n" +
	"\bRateResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12$\n" +
	"\x0enew_avg_rating\x18\x03 \x01(\x01R\fnewAvgRating\x12(\n" +
	"\x10new_rating_count\x18\x04 \x01(\x05R\x0enewRatingCount\x12$\n" +
	"\x0enew_shit_score\x18\x05 \x01(\x01R\fnewShitScore2\xc6\x01\n" +
	"\x06Rating\x123\n" +
	"\tRatePaper\x12\x14.rating.RatePaperReq\x1a\x10.rating.RateResp\x12D\n" +
	"\x0fGetPaperRatings\x12\x17.rating.PaperRatingsReq\x1a\x18.rating.PaperRatingsResp\x12A\n" +
	"\x0eGetUserRatings\x12\x16.rating.UserRatingsReq\x1a\x17.rating.UserRatingsRespB\n" +
	"Z\b./ratingb\x06proto3"

var (
	file_proto_rating_proto_rawDescOnce sync.Once
	file_proto_rating_proto_rawDescData []byte
)

func file_proto_rating_proto_rawDescGZIP() []byte {
	file_proto_rating_proto_rawDescOnce.Do(func() {
		file_proto_rating_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_rating_proto_rawDesc), len(file_proto_rating_proto_rawDesc)))
	})
	return file_proto_rating_proto_rawDescData
}

var file_proto_rating_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_rating_proto_goTypes = []any{
	(*RatePaperReq)(nil),     // 0: rating.RatePaperReq
	(*RatingItem)(nil),       // 1: rating.RatingItem
	(*PaperRatingsReq)(nil),  // 2: rating.PaperRatingsReq
	(*PaperRatingsResp)(nil), // 3: rating.PaperRatingsResp
	(*UserRatingsReq)(nil),   // 4: rating.UserRatingsReq
	(*UserRatingsResp)(nil),  // 5: rating.UserRatingsResp
	(*RateResp)(nil),         // 6: rating.RateResp
}
var file_proto_rating_proto_depIdxs = []int32{
	1, // 0: rating.PaperRatingsResp.items:type_name -> rating.RatingItem
	1, // 1: rating.UserRatingsResp.items:type_name -> rating.RatingItem
	0, // 2: rating.Rating.RatePaper:input_type -> rating.RatePaperReq
	2, // 3: rating.Rating.GetPaperRatings:input_type -> rating.PaperRatingsReq
	4, // 4: rating.Rating.GetUserRatings:input_type -> rating.UserRatingsReq
	6, // 5: rating.Rating.RatePaper:output_type -> rating.RateResp
	3, // 6: rating.Rating.GetPaperRatings:output_type -> rating.PaperRatingsResp
	5, // 7: rating.Rating.GetUserRatings:output_type -> rating.UserRatingsResp
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_rating_proto_init() }
func file_proto_rating_proto_init() {
	if File_proto_rating_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_rating_proto_rawDesc), len(file_proto_rating_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_rating_proto_goTypes,
		DependencyIndexes: file_proto_rating_proto_depIdxs,
		MessageInfos:      file_proto_rating_proto_msgTypes,
	}.Build()
	File_proto_rating_proto = out.File
	file_proto_rating_proto_goTypes = nil
	file_proto_rating_proto_depIdxs = nil
}
