// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: proto/admin.proto

package admin

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Common types
type CommonResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommonResp) Reset() {
	*x = CommonResp{}
	mi := &file_proto_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommonResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonResp) ProtoMessage() {}

func (x *CommonResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonResp.ProtoReflect.Descriptor instead.
func (*CommonResp) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{0}
}

func (x *CommonResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CommonResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// User Management
type UserItem struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username          string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Email             string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Nickname          string                 `protobuf:"bytes,4,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Role              int32                  `protobuf:"varint,5,opt,name=role,proto3" json:"role,omitempty"`
	ContributionScore string                 `protobuf:"bytes,6,opt,name=contribution_score,json=contributionScore,proto3" json:"contribution_score,omitempty"`
	Status            int32                  `protobuf:"varint,7,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt         int64                  `protobuf:"varint,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UserItem) Reset() {
	*x = UserItem{}
	mi := &file_proto_admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserItem) ProtoMessage() {}

func (x *UserItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserItem.ProtoReflect.Descriptor instead.
func (*UserItem) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{1}
}

func (x *UserItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserItem) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserItem) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserItem) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *UserItem) GetRole() int32 {
	if x != nil {
		return x.Role
	}
	return 0
}

func (x *UserItem) GetContributionScore() string {
	if x != nil {
		return x.ContributionScore
	}
	return ""
}

func (x *UserItem) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *UserItem) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type ListUsersReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersReq) Reset() {
	*x = ListUsersReq{}
	mi := &file_proto_admin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersReq) ProtoMessage() {}

func (x *ListUsersReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersReq.ProtoReflect.Descriptor instead.
func (*ListUsersReq) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{2}
}

func (x *ListUsersReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListUsersReq) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListUsersResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*UserItem            `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersResp) Reset() {
	*x = ListUsersResp{}
	mi := &file_proto_admin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersResp) ProtoMessage() {}

func (x *ListUsersResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersResp.ProtoReflect.Descriptor instead.
func (*ListUsersResp) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{3}
}

func (x *ListUsersResp) GetItems() []*UserItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListUsersResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type UpdateUserRoleReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Role          int32                  `protobuf:"varint,2,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserRoleReq) Reset() {
	*x = UpdateUserRoleReq{}
	mi := &file_proto_admin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserRoleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserRoleReq) ProtoMessage() {}

func (x *UpdateUserRoleReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserRoleReq.ProtoReflect.Descriptor instead.
func (*UpdateUserRoleReq) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateUserRoleReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateUserRoleReq) GetRole() int32 {
	if x != nil {
		return x.Role
	}
	return 0
}

type UpdateUserStatusReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Status        int32                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserStatusReq) Reset() {
	*x = UpdateUserStatusReq{}
	mi := &file_proto_admin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserStatusReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserStatusReq) ProtoMessage() {}

func (x *UpdateUserStatusReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserStatusReq.ProtoReflect.Descriptor instead.
func (*UpdateUserStatusReq) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateUserStatusReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateUserStatusReq) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

// Paper Management
type PaperItem struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title            string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	AuthorId         int64                  `protobuf:"varint,3,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	AuthorName       string                 `protobuf:"bytes,4,opt,name=author_name,json=authorName,proto3" json:"author_name,omitempty"`
	Zone             string                 `protobuf:"bytes,5,opt,name=zone,proto3" json:"zone,omitempty"`
	Status           int32                  `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`
	DegradationLevel int32                  `protobuf:"varint,7,opt,name=degradation_level,json=degradationLevel,proto3" json:"degradation_level,omitempty"`
	CreatedAt        int64                  `protobuf:"varint,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ShitScore        float64                `protobuf:"fixed64,9,opt,name=shit_score,json=shitScore,proto3" json:"shit_score,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PaperItem) Reset() {
	*x = PaperItem{}
	mi := &file_proto_admin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaperItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaperItem) ProtoMessage() {}

func (x *PaperItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaperItem.ProtoReflect.Descriptor instead.
func (*PaperItem) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{6}
}

func (x *PaperItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PaperItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *PaperItem) GetAuthorId() int64 {
	if x != nil {
		return x.AuthorId
	}
	return 0
}

func (x *PaperItem) GetAuthorName() string {
	if x != nil {
		return x.AuthorName
	}
	return ""
}

func (x *PaperItem) GetZone() string {
	if x != nil {
		return x.Zone
	}
	return ""
}

func (x *PaperItem) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *PaperItem) GetDegradationLevel() int32 {
	if x != nil {
		return x.DegradationLevel
	}
	return 0
}

func (x *PaperItem) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *PaperItem) GetShitScore() float64 {
	if x != nil {
		return x.ShitScore
	}
	return 0
}

type ListPapersReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Zone          string                 `protobuf:"bytes,3,opt,name=zone,proto3" json:"zone,omitempty"`
	Status        int32                  `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPapersReq) Reset() {
	*x = ListPapersReq{}
	mi := &file_proto_admin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPapersReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPapersReq) ProtoMessage() {}

func (x *ListPapersReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPapersReq.ProtoReflect.Descriptor instead.
func (*ListPapersReq) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{7}
}

func (x *ListPapersReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListPapersReq) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListPapersReq) GetZone() string {
	if x != nil {
		return x.Zone
	}
	return ""
}

func (x *ListPapersReq) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type ListPapersResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*PaperItem           `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPapersResp) Reset() {
	*x = ListPapersResp{}
	mi := &file_proto_admin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPapersResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPapersResp) ProtoMessage() {}

func (x *ListPapersResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPapersResp.ProtoReflect.Descriptor instead.
func (*ListPapersResp) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{8}
}

func (x *ListPapersResp) GetItems() []*PaperItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListPapersResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type UpdatePaperStatusReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaperId       int64                  `protobuf:"varint,1,opt,name=paper_id,json=paperId,proto3" json:"paper_id,omitempty"`
	Status        int32                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePaperStatusReq) Reset() {
	*x = UpdatePaperStatusReq{}
	mi := &file_proto_admin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePaperStatusReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePaperStatusReq) ProtoMessage() {}

func (x *UpdatePaperStatusReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePaperStatusReq.ProtoReflect.Descriptor instead.
func (*UpdatePaperStatusReq) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{9}
}

func (x *UpdatePaperStatusReq) GetPaperId() int64 {
	if x != nil {
		return x.PaperId
	}
	return 0
}

func (x *UpdatePaperStatusReq) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type UpdatePaperZoneReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaperId       int64                  `protobuf:"varint,1,opt,name=paper_id,json=paperId,proto3" json:"paper_id,omitempty"`
	Zone          string                 `protobuf:"bytes,2,opt,name=zone,proto3" json:"zone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePaperZoneReq) Reset() {
	*x = UpdatePaperZoneReq{}
	mi := &file_proto_admin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePaperZoneReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePaperZoneReq) ProtoMessage() {}

func (x *UpdatePaperZoneReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePaperZoneReq.ProtoReflect.Descriptor instead.
func (*UpdatePaperZoneReq) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{10}
}

func (x *UpdatePaperZoneReq) GetPaperId() int64 {
	if x != nil {
		return x.PaperId
	}
	return 0
}

func (x *UpdatePaperZoneReq) GetZone() string {
	if x != nil {
		return x.Zone
	}
	return ""
}

// Flag (Report) Management
type FlagItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TargetType    string                 `protobuf:"bytes,2,opt,name=target_type,json=targetType,proto3" json:"target_type,omitempty"`
	TargetId      int64                  `protobuf:"varint,3,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	ReporterId    int64                  `protobuf:"varint,4,opt,name=reporter_id,json=reporterId,proto3" json:"reporter_id,omitempty"`
	Reason        string                 `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`
	Detail        string                 `protobuf:"bytes,6,opt,name=detail,proto3" json:"detail,omitempty"`
	Status        int32                  `protobuf:"varint,7,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlagItem) Reset() {
	*x = FlagItem{}
	mi := &file_proto_admin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlagItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlagItem) ProtoMessage() {}

func (x *FlagItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlagItem.ProtoReflect.Descriptor instead.
func (*FlagItem) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{11}
}

func (x *FlagItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *FlagItem) GetTargetType() string {
	if x != nil {
		return x.TargetType
	}
	return ""
}

func (x *FlagItem) GetTargetId() int64 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

func (x *FlagItem) GetReporterId() int64 {
	if x != nil {
		return x.ReporterId
	}
	return 0
}

func (x *FlagItem) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *FlagItem) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *FlagItem) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *FlagItem) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type ListFlagsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Status        int32                  `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFlagsReq) Reset() {
	*x = ListFlagsReq{}
	mi := &file_proto_admin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFlagsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFlagsReq) ProtoMessage() {}

func (x *ListFlagsReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFlagsReq.ProtoReflect.Descriptor instead.
func (*ListFlagsReq) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{12}
}

func (x *ListFlagsReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListFlagsReq) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListFlagsReq) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type ListFlagsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*FlagItem            `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFlagsResp) Reset() {
	*x = ListFlagsResp{}
	mi := &file_proto_admin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFlagsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFlagsResp) ProtoMessage() {}

func (x *ListFlagsResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFlagsResp.ProtoReflect.Descriptor instead.
func (*ListFlagsResp) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{13}
}

func (x *ListFlagsResp) GetItems() []*FlagItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListFlagsResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type ResolveFlagReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FlagId        int64                  `protobuf:"varint,1,opt,name=flag_id,json=flagId,proto3" json:"flag_id,omitempty"`
	Status        int32                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveFlagReq) Reset() {
	*x = ResolveFlagReq{}
	mi := &file_proto_admin_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveFlagReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveFlagReq) ProtoMessage() {}

func (x *ResolveFlagReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveFlagReq.ProtoReflect.Descriptor instead.
func (*ResolveFlagReq) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{14}
}

func (x *ResolveFlagReq) GetFlagId() int64 {
	if x != nil {
		return x.FlagId
	}
	return 0
}

func (x *ResolveFlagReq) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

// Audit
type RecordAuditLogReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ActorUserId    int64                  `protobuf:"varint,1,opt,name=actor_user_id,json=actorUserId,proto3" json:"actor_user_id,omitempty"`
	PermissionCode string                 `protobuf:"bytes,2,opt,name=permission_code,json=permissionCode,proto3" json:"permission_code,omitempty"`
	Action         string                 `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	TargetType     string                 `protobuf:"bytes,4,opt,name=target_type,json=targetType,proto3" json:"target_type,omitempty"`
	TargetId       int64                  `protobuf:"varint,5,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	Detail         string                 `protobuf:"bytes,6,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RecordAuditLogReq) Reset() {
	*x = RecordAuditLogReq{}
	mi := &file_proto_admin_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordAuditLogReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordAuditLogReq) ProtoMessage() {}

func (x *RecordAuditLogReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordAuditLogReq.ProtoReflect.Descriptor instead.
func (*RecordAuditLogReq) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{15}
}

func (x *RecordAuditLogReq) GetActorUserId() int64 {
	if x != nil {
		return x.ActorUserId
	}
	return 0
}

func (x *RecordAuditLogReq) GetPermissionCode() string {
	if x != nil {
		return x.PermissionCode
	}
	return ""
}

func (x *RecordAuditLogReq) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *RecordAuditLogReq) GetTargetType() string {
	if x != nil {
		return x.TargetType
	}
	return ""
}

func (x *RecordAuditLogReq) GetTargetId() int64 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

func (x *RecordAuditLogReq) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

var File_proto_admin_proto protoreflect.FileDescriptor

const file_proto_admin_proto_rawDesc = "" +
	"\n" +
	"\x11proto/admin.proto\x12\x05admin\"@\n" +
	"\n" +
	"CommonResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xe2\x01\n" +
	"\bUserItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x1a\n" +
	"\bnickname\x18\x04 \x01(\tR\bnickname\x12\x12\n" +
	"\x04role\x18\x05 \x01(\x05R\x04role\x12-\n" +
	"\x12contribution_score\x18\x06 \x01(\tR\x11contributionScore\x12\x16\n" +
	"\x06status\x18\a \x01(\x05R\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\x03R\tcreatedAt\"?\n" +
	"\fListUsersReq\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\"L\n" +
	"\rListUsersResp\x12%\n" +
	"\x05items\x18\x01 \x03(\v2\x0f.admin.UserItemR\x05items\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"@\n" +
	"\x11UpdateUserRoleReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04role\x18\x02 \x01(\x05R\x04role\"F\n" +
	"\x13UpdateUserStatusReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\"\x86\x02\n" +
	"\tPaperItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1b\n" +
	"\tauthor_id\x18\x03 \x01(\x03R\bauthorId\x12\x1f\n" +
	"\vauthor_name\x18\x04 \x01(\tR\n" +
	"authorName\x12\x12\n" +
	"\x04zone\x18\x05 \x01(\tR\x04zone\x12\x16\n" +
	"\x06status\x18\x06 \x01(\x05R\x06status\x12+\n" +
	"\x11degradation_level\x18\a \x01(\x05R\x10degradationLevel\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"shit_score\x18\t \x01(\x01R\tshitScore\"l\n" +
	"\rListPapersReq\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x12\n" +
	"\x04zone\x18\x03 \x01(\tR\x04zone\x12\x16\n" +
	"\x06status\x18\x04 \x01(\x05R\x06status\"N\n" +
	"\x0eListPapersResp\x12&\n" +
	"\x05items\x18\x01 \x03(\v2\x10.admin.PaperItemR\x05items\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"I\n" +
	"\x14UpdatePaperStatusReq\x12\x19\n" +
	"\bpaper_id\x18\x01 \x01(\x03R\apaperId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\"C\n" +
	"\x12UpdatePaperZoneReq\x12\x19\n" +
	"\bpaper_id\x18\x01 \x01(\x03R\apaperId\x12\x12\n" +
	"\x04zone\x18\x02 \x01(\tR\x04zone\"\xe0\x01\n" +
	"\bFlagItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1f\n" +
	"\vtarget_type\x18\x02 \x01(\tR\n" +
	"targetType\x12\x1b\n" +
	"\ttarget_id\x18\x03 \x01(\x03R\btargetId\x12\x1f\n" +
	"\vreporter_id\x18\x04 \x01(\x03R\n" +
	"reporterId\x12\x16\n" +
	"\x06reason\x18\x05 \x01(\tR\x06reason\x12\x16\n" +
	"\x06detail\x18\x06 \x01(\tR\x06detail\x12\x16\n" +
	"\x06status\x18\a \x01(\x05R\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\x03R\tcreatedAt\"W\n" +
	"\fListFlagsReq\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x16\n" +
	"\x06status\x18\x03 \x01(\x05R\x06status\"L\n" +
	"\rListFlagsResp\x12%\n" +
	"\x05items\x18\x01 \x03(\v2\x0f.admin.FlagItemR\x05items\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"A\n" +
	"\x0eResolveFlagReq\x12\x17\n" +
	"\aflag_id\x18\x01 \x01(\x03R\x06flagId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\"\xce\x01\n" +
	"\x11RecordAuditLogReq\x12\"\n" +
	"\ractor_user_id\x18\x01 \x01(\x03R\vactorUserId\x12'\n" +
	"\x0fpermission_code\x18\x02 \x01(\tR\x0epermissionCode\x12\x16\n" +
	"\x06action\x18\x03 \x01(\tR\x06action\x12\x1f\n" +
	"\vtarget_type\x18\x04 \x01(\tR\n" +
	"targetType\x12\x1b\n" +
	"\ttarget_id\x18\x05 \x01(\x03R\btargetId\x12\x16\n" +
	"\x06detail\x18\x06 \x01(\tR\x06detail2\xb2\x04\n" +
	"\x05Admin\x126\n" +
	"\tListUsers\x12\x13.admin.ListUsersReq\x1a\x14.admin.ListUsersResp\x12=\n" +
	"\x0eUpdateUserRole\x12\x18.admin.UpdateUserRoleReq\x1a\x11.admin.CommonResp\x12A\n" +
	"\x10UpdateUserStatus\x12\x1a.admin.UpdateUserStatusReq\x1a\x11.admin.CommonResp\x129\n" +
	"\n" +
	"ListPapers\x12\x14.admin.ListPapersReq\x1a\x15.admin.ListPapersResp\x12C\n" +
	"\x11UpdatePaperStatus\x12\x1b.admin.UpdatePaperStatusReq\x1a\x11.admin.CommonResp\x12?\n" +
	"\x0fUpdatePaperZone\x12\x19.admin.UpdatePaperZoneReq\x1a\x11.admin.CommonResp\x126\n" +
	"\tListFlags\x12\x13.admin.ListFlagsReq\x1a\x14.admin.ListFlagsResp\x127\n" +
	"\vResolveFlag\x12\x15.admin.ResolveFlagReq\x1a\x11.admin.CommonResp\x12=\n" +
	"\x0eRecordAuditLog\x12\x18.admin.RecordAuditLogReq\x1a\x11.admin.CommonRespB\tZ\a./adminb\x06proto3"

var (
	file_proto_admin_proto_rawDescOnce sync.Once
	file_proto_admin_proto_rawDescData []byte
)

func file_proto_admin_proto_rawDescGZIP() []byte {
	file_proto_admin_proto_rawDescOnce.Do(func() {
		file_proto_admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_admin_proto_rawDesc), len(file_proto_admin_proto_rawDesc)))
	})
	return file_proto_admin_proto_rawDescData
}

var file_proto_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_proto_admin_proto_goTypes = []any{
	(*CommonResp)(nil),           // 0: admin.CommonResp
	(*UserItem)(nil),             // 1: admin.UserItem
	(*ListUsersReq)(nil),         // 2: admin.ListUsersReq
	(*ListUsersResp)(nil),        // 3: admin.ListUsersResp
	(*UpdateUserRoleReq)(nil),    // 4: admin.UpdateUserRoleReq
	(*UpdateUserStatusReq)(nil),  // 5: admin.UpdateUserStatusReq
	(*PaperItem)(nil),            // 6: admin.PaperItem
	(*ListPapersReq)(nil),        // 7: admin.ListPapersReq
	(*ListPapersResp)(nil),       // 8: admin.ListPapersResp
	(*UpdatePaperStatusReq)(nil), // 9: admin.UpdatePaperStatusReq
	(*UpdatePaperZoneReq)(nil),   // 10: admin.UpdatePaperZoneReq
	(*FlagItem)(nil),             // 11: admin.FlagItem
	(*ListFlagsReq)(nil),         // 12: admin.ListFlagsReq
	(*ListFlagsResp)(nil),        // 13: admin.ListFlagsResp
	(*ResolveFlagReq)(nil),       // 14: admin.ResolveFlagReq
	(*RecordAuditLogReq)(nil),    // 15: admin.RecordAuditLogReq
}
var file_proto_admin_proto_depIdxs = []int32{
	1,  // 0: admin.ListUsersResp.items:type_name -> admin.UserItem
	6,  // 1: admin.ListPapersResp.items:type_name -> admin.PaperItem
	11, // 2: admin.ListFlagsResp.items:type_name -> admin.FlagItem
	2,  // 3: admin.Admin.ListUsers:input_type -> admin.ListUsersReq
	4,  // 4: admin.Admin.UpdateUserRole:input_type -> admin.UpdateUserRoleReq
	5,  // 5: admin.Admin.UpdateUserStatus:input_type -> admin.UpdateUserStatusReq
	7,  // 6: admin.Admin.ListPapers:input_type -> admin.ListPapersReq
	9,  // 7: admin.Admin.UpdatePaperStatus:input_type -> admin.UpdatePaperStatusReq
	10, // 8: admin.Admin.UpdatePaperZone:input_type -> admin.UpdatePaperZoneReq
	12, // 9: admin.Admin.ListFlags:input_type -> admin.ListFlagsReq
	14, // 10: admin.Admin.ResolveFlag:input_type -> admin.ResolveFlagReq
	15, // 11: admin.Admin.RecordAuditLog:input_type -> admin.RecordAuditLogReq
	3,  // 12: admin.Admin.ListUsers:output_type -> admin.ListUsersResp
	0,  // 13: admin.Admin.UpdateUserRole:output_type -> admin.CommonResp
	0,  // 14: admin.Admin.UpdateUserStatus:output_type -> admin.CommonResp
	8,  // 15: admin.Admin.ListPapers:output_type -> admin.ListPapersResp
	0,  // 16: admin.Admin.UpdatePaperStatus:output_type -> admin.CommonResp
	0,  // 17: admin.Admin.UpdatePaperZone:output_type -> admin.CommonResp
	13, // 18: admin.Admin.ListFlags:output_type -> admin.ListFlagsResp
	0,  // 19: admin.Admin.ResolveFlag:output_type -> admin.CommonResp
	0,  // 20: admin.Admin.RecordAuditLog:output_type -> admin.CommonResp
	12, // [12:21] is the sub-list for method output_type
	3,  // [3:12] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_proto_admin_proto_init() }
func file_proto_admin_proto_init() {
	if File_proto_admin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_admin_proto_rawDesc), len(file_proto_admin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_admin_proto_goTypes,
		DependencyIndexes: file_proto_admin_proto_depIdxs,
		MessageInfos:      file_proto_admin_proto_msgTypes,
	}.Build()
	File_proto_admin_proto = out.File
	file_proto_admin_proto_goTypes = nil
	file_proto_admin_proto_depIdxs = nil
}
