// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: proto/admin.proto

package admin

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Admin_ListUsers_FullMethodName          = "/admin.Admin/ListUsers"
	Admin_UpdateUserRole_FullMethodName     = "/admin.Admin/UpdateUserRole"
	Admin_UpdateUserStatus_FullMethodName   = "/admin.Admin/UpdateUserStatus"
	Admin_ListPapers_FullMethodName         = "/admin.Admin/ListPapers"
	Admin_UpdatePaperStatus_FullMethodName  = "/admin.Admin/UpdatePaperStatus"
	Admin_UpdatePaperZone_FullMethodName    = "/admin.Admin/UpdatePaperZone"
	Admin_ListFlags_FullMethodName          = "/admin.Admin/ListFlags"
	Admin_ResolveFlag_FullMethodName        = "/admin.Admin/ResolveFlag"
	Admin_RecordAuditLog_FullMethodName     = "/admin.Admin/RecordAuditLog"
	Admin_ListAuditLogs_FullMethodName      = "/admin.Admin/ListAuditLogs"
	Admin_ListRoles_FullMethodName          = "/admin.Admin/ListRoles"
	Admin_CreateRole_FullMethodName         = "/admin.Admin/CreateRole"
	Admin_UpdateRole_FullMethodName         = "/admin.Admin/UpdateRole"
	Admin_DeleteRole_FullMethodName         = "/admin.Admin/DeleteRole"
	Admin_ListPermissions_FullMethodName    = "/admin.Admin/ListPermissions"
	Admin_GetRolePermissions_FullMethodName = "/admin.Admin/GetRolePermissions"
	Admin_SetRolePermissions_FullMethodName = "/admin.Admin/SetRolePermissions"
	Admin_ListUserRoles_FullMethodName      = "/admin.Admin/ListUserRoles"
	Admin_AssignUserRole_FullMethodName     = "/admin.Admin/AssignUserRole"
	Admin_RevokeUserRole_FullMethodName     = "/admin.Admin/RevokeUserRole"
)

// AdminClient is the client API for Admin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AdminClient interface {
	// User
	ListUsers(ctx context.Context, in *ListUsersReq, opts ...grpc.CallOption) (*ListUsersResp, error)
	UpdateUserRole(ctx context.Context, in *UpdateUserRoleReq, opts ...grpc.CallOption) (*CommonResp, error)
	UpdateUserStatus(ctx context.Context, in *UpdateUserStatusReq, opts ...grpc.CallOption) (*CommonResp, error)
	// Paper
	ListPapers(ctx context.Context, in *ListPapersReq, opts ...grpc.CallOption) (*ListPapersResp, error)
	UpdatePaperStatus(ctx context.Context, in *UpdatePaperStatusReq, opts ...grpc.CallOption) (*CommonResp, error)
	UpdatePaperZone(ctx context.Context, in *UpdatePaperZoneReq, opts ...grpc.CallOption) (*CommonResp, error)
	// Flag
	ListFlags(ctx context.Context, in *ListFlagsReq, opts ...grpc.CallOption) (*ListFlagsResp, error)
	ResolveFlag(ctx context.Context, in *ResolveFlagReq, opts ...grpc.CallOption) (*CommonResp, error)
	// Audit
	RecordAuditLog(ctx context.Context, in *RecordAuditLogReq, opts ...grpc.CallOption) (*CommonResp, error)
	ListAuditLogs(ctx context.Context, in *ListAuditLogsReq, opts ...grpc.CallOption) (*ListAuditLogsResp, error)
	// RBAC - Role
	ListRoles(ctx context.Context, in *ListRolesReq, opts ...grpc.CallOption) (*ListRolesResp, error)
	CreateRole(ctx context.Context, in *CreateRoleReq, opts ...grpc.CallOption) (*CreateRoleResp, error)
	UpdateRole(ctx context.Context, in *UpdateRoleReq, opts ...grpc.CallOption) (*CommonResp, error)
	DeleteRole(ctx context.Context, in *DeleteRoleReq, opts ...grpc.CallOption) (*CommonResp, error)
	// RBAC - Permission
	ListPermissions(ctx context.Context, in *ListPermissionsReq, opts ...grpc.CallOption) (*ListPermissionsResp, error)
	// RBAC - Role-Permission
	GetRolePermissions(ctx context.Context, in *GetRolePermissionsReq, opts ...grpc.CallOption) (*GetRolePermissionsResp, error)
	SetRolePermissions(ctx context.Context, in *SetRolePermissionsReq, opts ...grpc.CallOption) (*CommonResp, error)
	// RBAC - User-Role
	ListUserRoles(ctx context.Context, in *ListUserRolesReq, opts ...grpc.CallOption) (*ListUserRolesResp, error)
	AssignUserRole(ctx context.Context, in *AssignUserRoleReq, opts ...grpc.CallOption) (*CommonResp, error)
	RevokeUserRole(ctx context.Context, in *RevokeUserRoleReq, opts ...grpc.CallOption) (*CommonResp, error)
}

type adminClient struct {
	cc grpc.ClientConnInterface
}

func NewAdminClient(cc grpc.ClientConnInterface) AdminClient {
	return &adminClient{cc}
}

func (c *adminClient) ListUsers(ctx context.Context, in *ListUsersReq, opts ...grpc.CallOption) (*ListUsersResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListUsersResp)
	err := c.cc.Invoke(ctx, Admin_ListUsers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) UpdateUserRole(ctx context.Context, in *UpdateUserRoleReq, opts ...grpc.CallOption) (*CommonResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResp)
	err := c.cc.Invoke(ctx, Admin_UpdateUserRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) UpdateUserStatus(ctx context.Context, in *UpdateUserStatusReq, opts ...grpc.CallOption) (*CommonResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResp)
	err := c.cc.Invoke(ctx, Admin_UpdateUserStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) ListPapers(ctx context.Context, in *ListPapersReq, opts ...grpc.CallOption) (*ListPapersResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPapersResp)
	err := c.cc.Invoke(ctx, Admin_ListPapers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) UpdatePaperStatus(ctx context.Context, in *UpdatePaperStatusReq, opts ...grpc.CallOption) (*CommonResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResp)
	err := c.cc.Invoke(ctx, Admin_UpdatePaperStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) UpdatePaperZone(ctx context.Context, in *UpdatePaperZoneReq, opts ...grpc.CallOption) (*CommonResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResp)
	err := c.cc.Invoke(ctx, Admin_UpdatePaperZone_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) ListFlags(ctx context.Context, in *ListFlagsReq, opts ...grpc.CallOption) (*ListFlagsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListFlagsResp)
	err := c.cc.Invoke(ctx, Admin_ListFlags_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) ResolveFlag(ctx context.Context, in *ResolveFlagReq, opts ...grpc.CallOption) (*CommonResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResp)
	err := c.cc.Invoke(ctx, Admin_ResolveFlag_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) RecordAuditLog(ctx context.Context, in *RecordAuditLogReq, opts ...grpc.CallOption) (*CommonResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResp)
	err := c.cc.Invoke(ctx, Admin_RecordAuditLog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) ListAuditLogs(ctx context.Context, in *ListAuditLogsReq, opts ...grpc.CallOption) (*ListAuditLogsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAuditLogsResp)
	err := c.cc.Invoke(ctx, Admin_ListAuditLogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) ListRoles(ctx context.Context, in *ListRolesReq, opts ...grpc.CallOption) (*ListRolesResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRolesResp)
	err := c.cc.Invoke(ctx, Admin_ListRoles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) CreateRole(ctx context.Context, in *CreateRoleReq, opts ...grpc.CallOption) (*CreateRoleResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateRoleResp)
	err := c.cc.Invoke(ctx, Admin_CreateRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) UpdateRole(ctx context.Context, in *UpdateRoleReq, opts ...grpc.CallOption) (*CommonResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResp)
	err := c.cc.Invoke(ctx, Admin_UpdateRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) DeleteRole(ctx context.Context, in *DeleteRoleReq, opts ...grpc.CallOption) (*CommonResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResp)
	err := c.cc.Invoke(ctx, Admin_DeleteRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) ListPermissions(ctx context.Context, in *ListPermissionsReq, opts ...grpc.CallOption) (*ListPermissionsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPermissionsResp)
	err := c.cc.Invoke(ctx, Admin_ListPermissions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) GetRolePermissions(ctx context.Context, in *GetRolePermissionsReq, opts ...grpc.CallOption) (*GetRolePermissionsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRolePermissionsResp)
	err := c.cc.Invoke(ctx, Admin_GetRolePermissions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) SetRolePermissions(ctx context.Context, in *SetRolePermissionsReq, opts ...grpc.CallOption) (*CommonResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResp)
	err := c.cc.Invoke(ctx, Admin_SetRolePermissions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) ListUserRoles(ctx context.Context, in *ListUserRolesReq, opts ...grpc.CallOption) (*ListUserRolesResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListUserRolesResp)
	err := c.cc.Invoke(ctx, Admin_ListUserRoles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) AssignUserRole(ctx context.Context, in *AssignUserRoleReq, opts ...grpc.CallOption) (*CommonResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResp)
	err := c.cc.Invoke(ctx, Admin_AssignUserRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) RevokeUserRole(ctx context.Context, in *RevokeUserRoleReq, opts ...grpc.CallOption) (*CommonResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResp)
	err := c.cc.Invoke(ctx, Admin_RevokeUserRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdminServer is the server API for Admin service.
// All implementations must embed UnimplementedAdminServer
// for forward compatibility.
type AdminServer interface {
	// User
	ListUsers(context.Context, *ListUsersReq) (*ListUsersResp, error)
	UpdateUserRole(context.Context, *UpdateUserRoleReq) (*CommonResp, error)
	UpdateUserStatus(context.Context, *UpdateUserStatusReq) (*CommonResp, error)
	// Paper
	ListPapers(context.Context, *ListPapersReq) (*ListPapersResp, error)
	UpdatePaperStatus(context.Context, *UpdatePaperStatusReq) (*CommonResp, error)
	UpdatePaperZone(context.Context, *UpdatePaperZoneReq) (*CommonResp, error)
	// Flag
	ListFlags(context.Context, *ListFlagsReq) (*ListFlagsResp, error)
	ResolveFlag(context.Context, *ResolveFlagReq) (*CommonResp, error)
	// Audit
	RecordAuditLog(context.Context, *RecordAuditLogReq) (*CommonResp, error)
	ListAuditLogs(context.Context, *ListAuditLogsReq) (*ListAuditLogsResp, error)
	// RBAC - Role
	ListRoles(context.Context, *ListRolesReq) (*ListRolesResp, error)
	CreateRole(context.Context, *CreateRoleReq) (*CreateRoleResp, error)
	UpdateRole(context.Context, *UpdateRoleReq) (*CommonResp, error)
	DeleteRole(context.Context, *DeleteRoleReq) (*CommonResp, error)
	// RBAC - Permission
	ListPermissions(context.Context, *ListPermissionsReq) (*ListPermissionsResp, error)
	// RBAC - Role-Permission
	GetRolePermissions(context.Context, *GetRolePermissionsReq) (*GetRolePermissionsResp, error)
	SetRolePermissions(context.Context, *SetRolePermissionsReq) (*CommonResp, error)
	// RBAC - User-Role
	ListUserRoles(context.Context, *ListUserRolesReq) (*ListUserRolesResp, error)
	AssignUserRole(context.Context, *AssignUserRoleReq) (*CommonResp, error)
	RevokeUserRole(context.Context, *RevokeUserRoleReq) (*CommonResp, error)
	mustEmbedUnimplementedAdminServer()
}

// UnimplementedAdminServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAdminServer struct{}

func (UnimplementedAdminServer) ListUsers(context.Context, *ListUsersReq) (*ListUsersResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListUsers not implemented")
}
func (UnimplementedAdminServer) UpdateUserRole(context.Context, *UpdateUserRoleReq) (*CommonResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUserRole not implemented")
}
func (UnimplementedAdminServer) UpdateUserStatus(context.Context, *UpdateUserStatusReq) (*CommonResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUserStatus not implemented")
}
func (UnimplementedAdminServer) ListPapers(context.Context, *ListPapersReq) (*ListPapersResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPapers not implemented")
}
func (UnimplementedAdminServer) UpdatePaperStatus(context.Context, *UpdatePaperStatusReq) (*CommonResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePaperStatus not implemented")
}
func (UnimplementedAdminServer) UpdatePaperZone(context.Context, *UpdatePaperZoneReq) (*CommonResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePaperZone not implemented")
}
func (UnimplementedAdminServer) ListFlags(context.Context, *ListFlagsReq) (*ListFlagsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListFlags not implemented")
}
func (UnimplementedAdminServer) ResolveFlag(context.Context, *ResolveFlagReq) (*CommonResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResolveFlag not implemented")
}
func (UnimplementedAdminServer) RecordAuditLog(context.Context, *RecordAuditLogReq) (*CommonResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RecordAuditLog not implemented")
}
func (UnimplementedAdminServer) ListAuditLogs(context.Context, *ListAuditLogsReq) (*ListAuditLogsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAuditLogs not implemented")
}
func (UnimplementedAdminServer) ListRoles(context.Context, *ListRolesReq) (*ListRolesResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListRoles not implemented")
}
func (UnimplementedAdminServer) CreateRole(context.Context, *CreateRoleReq) (*CreateRoleResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateRole not implemented")
}
func (UnimplementedAdminServer) UpdateRole(context.Context, *UpdateRoleReq) (*CommonResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateRole not implemented")
}
func (UnimplementedAdminServer) DeleteRole(context.Context, *DeleteRoleReq) (*CommonResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteRole not implemented")
}
func (UnimplementedAdminServer) ListPermissions(context.Context, *ListPermissionsReq) (*ListPermissionsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPermissions not implemented")
}
func (UnimplementedAdminServer) GetRolePermissions(context.Context, *GetRolePermissionsReq) (*GetRolePermissionsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRolePermissions not implemented")
}
func (UnimplementedAdminServer) SetRolePermissions(context.Context, *SetRolePermissionsReq) (*CommonResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetRolePermissions not implemented")
}
func (UnimplementedAdminServer) ListUserRoles(context.Context, *ListUserRolesReq) (*ListUserRolesResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListUserRoles not implemented")
}
func (UnimplementedAdminServer) AssignUserRole(context.Context, *AssignUserRoleReq) (*CommonResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AssignUserRole not implemented")
}
func (UnimplementedAdminServer) RevokeUserRole(context.Context, *RevokeUserRoleReq) (*CommonResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RevokeUserRole not implemented")
}
func (UnimplementedAdminServer) mustEmbedUnimplementedAdminServer() {}
func (UnimplementedAdminServer) testEmbeddedByValue()               {}

// UnsafeAdminServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdminServer will
// result in compilation errors.
type UnsafeAdminServer interface {
	mustEmbedUnimplementedAdminServer()
}

func RegisterAdminServer(s grpc.ServiceRegistrar, srv AdminServer) {
	// If the following call pancis, it indicates UnimplementedAdminServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Admin_ServiceDesc, srv)
}

func _Admin_ListUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUsersReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).ListUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_ListUsers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).ListUsers(ctx, req.(*ListUsersReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_UpdateUserRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserRoleReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).UpdateUserRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_UpdateUserRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).UpdateUserRole(ctx, req.(*UpdateUserRoleReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_UpdateUserStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserStatusReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).UpdateUserStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_UpdateUserStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).UpdateUserStatus(ctx, req.(*UpdateUserStatusReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_ListPapers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPapersReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).ListPapers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_ListPapers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).ListPapers(ctx, req.(*ListPapersReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_UpdatePaperStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePaperStatusReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).UpdatePaperStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_UpdatePaperStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).UpdatePaperStatus(ctx, req.(*UpdatePaperStatusReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_UpdatePaperZone_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePaperZoneReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).UpdatePaperZone(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_UpdatePaperZone_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).UpdatePaperZone(ctx, req.(*UpdatePaperZoneReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_ListFlags_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFlagsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).ListFlags(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_ListFlags_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).ListFlags(ctx, req.(*ListFlagsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_ResolveFlag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveFlagReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).ResolveFlag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_ResolveFlag_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).ResolveFlag(ctx, req.(*ResolveFlagReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_RecordAuditLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordAuditLogReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).RecordAuditLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_RecordAuditLog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).RecordAuditLog(ctx, req.(*RecordAuditLogReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_ListAuditLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAuditLogsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).ListAuditLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_ListAuditLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).ListAuditLogs(ctx, req.(*ListAuditLogsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_ListRoles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRolesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).ListRoles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_ListRoles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).ListRoles(ctx, req.(*ListRolesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_CreateRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRoleReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).CreateRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_CreateRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).CreateRole(ctx, req.(*CreateRoleReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_UpdateRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRoleReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).UpdateRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_UpdateRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).UpdateRole(ctx, req.(*UpdateRoleReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_DeleteRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRoleReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).DeleteRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_DeleteRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).DeleteRole(ctx, req.(*DeleteRoleReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_ListPermissions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPermissionsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).ListPermissions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_ListPermissions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).ListPermissions(ctx, req.(*ListPermissionsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_GetRolePermissions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRolePermissionsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).GetRolePermissions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_GetRolePermissions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).GetRolePermissions(ctx, req.(*GetRolePermissionsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_SetRolePermissions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetRolePermissionsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).SetRolePermissions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_SetRolePermissions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).SetRolePermissions(ctx, req.(*SetRolePermissionsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_ListUserRoles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUserRolesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).ListUserRoles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_ListUserRoles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).ListUserRoles(ctx, req.(*ListUserRolesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_AssignUserRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssignUserRoleReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).AssignUserRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_AssignUserRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).AssignUserRole(ctx, req.(*AssignUserRoleReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_RevokeUserRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeUserRoleReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).RevokeUserRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_RevokeUserRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).RevokeUserRole(ctx, req.(*RevokeUserRoleReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Admin_ServiceDesc is the grpc.ServiceDesc for Admin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Admin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "admin.Admin",
	HandlerType: (*AdminServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListUsers",
			Handler:    _Admin_ListUsers_Handler,
		},
		{
			MethodName: "UpdateUserRole",
			Handler:    _Admin_UpdateUserRole_Handler,
		},
		{
			MethodName: "UpdateUserStatus",
			Handler:    _Admin_UpdateUserStatus_Handler,
		},
		{
			MethodName: "ListPapers",
			Handler:    _Admin_ListPapers_Handler,
		},
		{
			MethodName: "UpdatePaperStatus",
			Handler:    _Admin_UpdatePaperStatus_Handler,
		},
		{
			MethodName: "UpdatePaperZone",
			Handler:    _Admin_UpdatePaperZone_Handler,
		},
		{
			MethodName: "ListFlags",
			Handler:    _Admin_ListFlags_Handler,
		},
		{
			MethodName: "ResolveFlag",
			Handler:    _Admin_ResolveFlag_Handler,
		},
		{
			MethodName: "RecordAuditLog",
			Handler:    _Admin_RecordAuditLog_Handler,
		},
		{
			MethodName: "ListAuditLogs",
			Handler:    _Admin_ListAuditLogs_Handler,
		},
		{
			MethodName: "ListRoles",
			Handler:    _Admin_ListRoles_Handler,
		},
		{
			MethodName: "CreateRole",
			Handler:    _Admin_CreateRole_Handler,
		},
		{
			MethodName: "UpdateRole",
			Handler:    _Admin_UpdateRole_Handler,
		},
		{
			MethodName: "DeleteRole",
			Handler:    _Admin_DeleteRole_Handler,
		},
		{
			MethodName: "ListPermissions",
			Handler:    _Admin_ListPermissions_Handler,
		},
		{
			MethodName: "GetRolePermissions",
			Handler:    _Admin_GetRolePermissions_Handler,
		},
		{
			MethodName: "SetRolePermissions",
			Handler:    _Admin_SetRolePermissions_Handler,
		},
		{
			MethodName: "ListUserRoles",
			Handler:    _Admin_ListUserRoles_Handler,
		},
		{
			MethodName: "AssignUserRole",
			Handler:    _Admin_AssignUserRole_Handler,
		},
		{
			MethodName: "RevokeUserRole",
			Handler:    _Admin_RevokeUserRole_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/admin.proto",
}
