// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: news.proto

package server

import (
	"context"

	"journal/rpc/news/internal/logic/news"
	"journal/rpc/news/internal/svc"
	"journal/rpc/news/news"
)

type NewsServer struct {
	svcCtx *svc.ServiceContext
	news.UnimplementedNewsServer
}

func NewNewsServer(svcCtx *svc.ServiceContext) *NewsServer {
	return &NewsServer{
		svcCtx: svcCtx,
	}
}

func (s *NewsServer) CreateNews(ctx context.Context, in *news.CreateNewsReq) (*news.CommonResp, error) {
	l := newslogic.NewCreateNewsLogic(ctx, s.svcCtx)
	return l.CreateNews(in)
}

func (s *NewsServer) ListNews(ctx context.Context, in *news.ListNewsReq) (*news.ListNewsResp, error) {
	l := newslogic.NewListNewsLogic(ctx, s.svcCtx)
	return l.ListNews(in)
}

func (s *NewsServer) GetNews(ctx context.Context, in *news.GetNewsReq) (*news.GetNewsResp, error) {
	l := newslogic.NewGetNewsLogic(ctx, s.svcCtx)
	return l.GetNews(in)
}
