global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'journal-api'
    static_configs:
      - targets: ['host.docker.internal:9105']
        labels:
          service: api-gateway

  - job_name: 'journal-user-rpc'
    static_configs:
      - targets: ['host.docker.internal:9101']
        labels:
          service: user-rpc

  - job_name: 'journal-paper-rpc'
    static_configs:
      - targets: ['host.docker.internal:9102']
        labels:
          service: paper-rpc

  - job_name: 'journal-rating-rpc'
    static_configs:
      - targets: ['host.docker.internal:9103']
        labels:
          service: rating-rpc

  - job_name: 'journal-news-rpc'
    static_configs:
      - targets: ['host.docker.internal:9104']
        labels:
          service: news-rpc
