apiVersion: v1
kind: Secret
metadata:
  name: journal-secrets
  namespace: journal
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "root123456"
  MYSQL_DATABASE: "journal"
  MYSQL_USER: "journal"
  MYSQL_PASSWORD: "journal123"
  REDIS_PASSWORD: "redis123456"
  JWT_SECRET: "journal-jwt-secret-key-2026"
