// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: news.proto

package news

import (
	"context"

	"journal/rpc/news/news"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CommonResp    = news.CommonResp
	CreateNewsReq = news.CreateNewsReq
	GetNewsReq    = news.GetNewsReq
	GetNewsResp   = news.GetNewsResp
	ListNewsReq   = news.ListNewsReq
	ListNewsResp  = news.ListNewsResp
	NewsItem      = news.NewsItem

	News interface {
		CreateNews(ctx context.Context, in *CreateNewsReq, opts ...grpc.CallOption) (*CommonResp, error)
		ListNews(ctx context.Context, in *ListNewsReq, opts ...grpc.CallOption) (*ListNewsResp, error)
		GetNews(ctx context.Context, in *GetNewsReq, opts ...grpc.CallOption) (*GetNewsResp, error)
	}

	defaultNews struct {
		cli zrpc.Client
	}
)

func NewNews(cli zrpc.Client) News {
	return &defaultNews{
		cli: cli,
	}
}

func (m *defaultNews) CreateNews(ctx context.Context, in *CreateNewsReq, opts ...grpc.CallOption) (*CommonResp, error) {
	client := news.NewNewsClient(m.cli.Conn())
	return client.CreateNews(ctx, in, opts...)
}

func (m *defaultNews) ListNews(ctx context.Context, in *ListNewsReq, opts ...grpc.CallOption) (*ListNewsResp, error) {
	client := news.NewNewsClient(m.cli.Conn())
	return client.ListNews(ctx, in, opts...)
}

func (m *defaultNews) GetNews(ctx context.Context, in *GetNewsReq, opts ...grpc.CallOption) (*GetNewsResp, error) {
	client := news.NewNewsClient(m.cli.Conn())
	return client.GetNews(ctx, in, opts...)
}
