// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: rating.proto

package server

import (
	"context"

	"journal/rpc/rating/internal/logic/rating"
	"journal/rpc/rating/internal/svc"
	"journal/rpc/rating/rating"
)

type RatingServer struct {
	svcCtx *svc.ServiceContext
	rating.UnimplementedRatingServer
}

func NewRatingServer(svcCtx *svc.ServiceContext) *RatingServer {
	return &RatingServer{
		svcCtx: svcCtx,
	}
}

func (s *RatingServer) RatePaper(ctx context.Context, in *rating.RatePaperReq) (*rating.RateResp, error) {
	l := ratinglogic.NewRatePaperLogic(ctx, s.svcCtx)
	return l.RatePaper(in)
}

func (s *RatingServer) GetPaperRatings(ctx context.Context, in *rating.PaperRatingsReq) (*rating.PaperRatingsResp, error) {
	l := ratinglogic.NewGetPaperRatingsLogic(ctx, s.svcCtx)
	return l.GetPaperRatings(in)
}

func (s *RatingServer) GetUserRatings(ctx context.Context, in *rating.UserRatingsReq) (*rating.UserRatingsResp, error) {
	l := ratinglogic.NewGetUserRatingsLogic(ctx, s.svcCtx)
	return l.GetUserRatings(in)
}
