// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: paper.proto

package server

import (
	"context"

	"journal/rpc/paper/internal/logic/paper"
	"journal/rpc/paper/internal/svc"
	"journal/rpc/paper/paper"
)

type PaperServer struct {
	svcCtx *svc.ServiceContext
	paper.UnimplementedPaperServer
}

func NewPaperServer(svcCtx *svc.ServiceContext) *PaperServer {
	return &PaperServer{
		svcCtx: svcCtx,
	}
}

func (s *PaperServer) SubmitPaper(ctx context.Context, in *paper.SubmitPaperReq) (*paper.SubmitPaperResp, error) {
	l := paperlogic.NewSubmitPaperLogic(ctx, s.svcCtx)
	return l.SubmitPaper(in)
}

func (s *PaperServer) GetPaper(ctx context.Context, in *paper.GetPaperReq) (*paper.GetPaperResp, error) {
	l := paperlogic.NewGetPaperLogic(ctx, s.svcCtx)
	return l.GetPaper(in)
}

func (s *PaperServer) ListPapers(ctx context.Context, in *paper.ListPapersReq) (*paper.ListPapersResp, error) {
	l := paperlogic.NewListPapersLogic(ctx, s.svcCtx)
	return l.ListPapers(in)
}

func (s *PaperServer) SearchPapers(ctx context.Context, in *paper.SearchPapersReq) (*paper.ListPapersResp, error) {
	l := paperlogic.NewSearchPapersLogic(ctx, s.svcCtx)
	return l.SearchPapers(in)
}

func (s *PaperServer) UpdateZone(ctx context.Context, in *paper.UpdateZoneReq) (*paper.CommonResp, error) {
	l := paperlogic.NewUpdateZoneLogic(ctx, s.svcCtx)
	return l.UpdateZone(in)
}

func (s *PaperServer) UserPapers(ctx context.Context, in *paper.UserPapersReq) (*paper.ListPapersResp, error) {
	l := paperlogic.NewUserPapersLogic(ctx, s.svcCtx)
	return l.UserPapers(in)
}

func (s *PaperServer) IncrViewCount(ctx context.Context, in *paper.GetPaperReq) (*paper.CommonResp, error) {
	l := paperlogic.NewIncrViewCountLogic(ctx, s.svcCtx)
	return l.IncrViewCount(in)
}
