// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type AdminLoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type AdminLoginResp struct {
	Token    string `json:"token"`
	ExpireAt int64  `json:"expire_at"`
}

type AssignUserRoleReq struct {
	UserId int64 `path:"id"`
	RoleId int64 `json:"role_id"`
}

type AuditLogItem struct {
	Id             int64  `json:"id"`
	ActorUserId    int64  `json:"actor_user_id"`
	PermissionCode string `json:"permission_code"`
	Action         string `json:"action"`
	TargetType     string `json:"target_type"`
	TargetId       int64  `json:"target_id"`
	Detail         string `json:"detail"`
	CreatedAt      int64  `json:"created_at"`
}

type CommonResp struct {
	Success bool   `json:"success"`
	Message string `json:"message"`
}

type CreateNewsReq struct {
	Title     string `json:"title" validate:"required"`
	TitleEn   string `json:"title_en,optional"`
	Content   string `json:"content" validate:"required"`
	ContentEn string `json:"content_en,optional"`
	Category  string `json:"category,optional,default=announcement"`
	IsPinned  bool   `json:"is_pinned,optional"`
}

type CreateKeywordRuleReq struct {
	Pattern   string `json:"pattern"`
	MatchType string `json:"match_type"`
	Category  string `json:"category"`
}

type CreateKeywordRuleResp struct {
	Success bool   `json:"success"`
	Message string `json:"message"`
	Id      int64  `json:"id"`
}

type CreateRoleReq struct {
	Code        string `json:"code"`
	Name        string `json:"name"`
	Description string `json:"description,optional"`
}

type CreateRoleResp struct {
	Id int64 `json:"id"`
}

type FlagItem struct {
	Id         int64  `json:"id"`
	TargetType string `json:"target_type"`
	TargetId   int64  `json:"target_id"`
	ReporterId int64  `json:"reporter_id"`
	Reason     string `json:"reason"`
	Detail     string `json:"detail"`
	Status     int32  `json:"status"`
	CreatedAt  int64  `json:"created_at"`
}

type GetRolePermissionsResp struct {
	PermissionIds []int64 `json:"permission_ids"`
}

type IdReq struct {
	Id int64 `path:"id"`
}

type ListAuditLogsResp struct {
	Items []AuditLogItem `json:"items"`
	Total int64          `json:"total"`
}

type ListFlagsReq struct {
	Page     int   `form:"page,optional,default=1"`
	PageSize int   `form:"page_size,optional,default=20"`
	Status   int32 `form:"status,optional,default=-1"`
}

type ListFlagsResp struct {
	Items []FlagItem `json:"items"`
	Total int64      `json:"total"`
}

type ListKeywordRulesResp struct {
	Items []KeywordRuleItem `json:"items"`
}

type ListPapersReq struct {
	Zone       string `form:"zone,optional"`
	Discipline string `form:"discipline,optional"`
	Sort       string `form:"sort,optional,default=newest"`
	Page       int    `form:"page,optional,default=1"`
	PageSize   int    `form:"page_size,optional,default=20"`
}

type ListPapersResp struct {
	Items []PaperItem `json:"items"`
	Total int64       `json:"total"`
}

type ListPermissionsResp struct {
	Items []PermissionItem `json:"items"`
}

type ListRolesResp struct {
	Items []RoleItem `json:"items"`
}

type ListUserRolesResp struct {
	Items []RoleItem `json:"items"`
}

type ListUsersRespAdmin struct {
	Items []UserItemAdmin `json:"items"`
	Total int64           `json:"total"`
}

type MyPermissionsResp struct {
	Permissions []string `json:"permissions"`
	IsSuper     bool     `json:"is_super"`
}

type KeywordRuleItem struct {
	Id            int64  `json:"id"`
	Pattern       string `json:"pattern"`
	MatchType     string `json:"match_type"`
	Category      string `json:"category"`
	Enabled       int32  `json:"enabled"`
	CreatorUserId int64  `json:"creator_user_id"`
	CreatedAt     int64  `json:"created_at"`
	UpdatedAt     int64  `json:"updated_at"`
}

type PageReq struct {
	Page     int `form:"page,optional,default=1"`
	PageSize int `form:"page_size,optional,default=20"`
}

type PaperItem struct {
	Id               int64   `json:"id"`
	Title            string  `json:"title"`
	TitleEn          string  `json:"title_en"`
	Abstract         string  `json:"abstract"`
	AbstractEn       string  `json:"abstract_en"`
	Content          string  `json:"content,omitempty"`
	AuthorId         int64   `json:"author_id"`
	AuthorName       string  `json:"author_name"`
	Discipline       string  `json:"discipline"`
	Zone             string  `json:"zone"`
	ShitScore        float64 `json:"shit_score"`
	AvgRating        float64 `json:"avg_rating"`
	RatingCount      int32   `json:"rating_count"`
	ViewCount        int32   `json:"view_count"`
	ControversyIndex float64 `json:"controversy_index"`
	Doi              string  `json:"doi"`
	Keywords         string  `json:"keywords"`
	FilePath         string  `json:"file_path"`
	Status           int32   `json:"status"`
	DegradationLevel int32   `json:"degradation_level"`
	CreatedAt        int64   `json:"created_at"`
	PromotedAt       int64   `json:"promoted_at"`
}

type PermissionItem struct {
	Id          int64  `json:"id"`
	Code        string `json:"code"`
	Name        string `json:"name"`
	Module      string `json:"module"`
	Resource    string `json:"resource"`
	Action      string `json:"action"`
	Description string `json:"description"`
	Status      int32  `json:"status"`
}

type ResolveFlagReq struct {
	FlagId int64 `path:"id"`
	Status int32 `json:"status"`
}

type RevokeUserRoleReq struct {
	UserId int64 `path:"id"`
	RoleId int64 `path:"roleId"`
}

type RoleItem struct {
	Id          int64  `json:"id"`
	Code        string `json:"code"`
	Name        string `json:"name"`
	Description string `json:"description"`
	IsSuper     int32  `json:"is_super"`
	Status      int32  `json:"status"`
	CreatedAt   int64  `json:"created_at"`
	UpdatedAt   int64  `json:"updated_at"`
}

type SetRolePermissionsReq struct {
	RoleId        int64   `path:"id"`
	PermissionIds []int64 `json:"permission_ids"`
}

type UpdatePaperStatusReq struct {
	PaperId int64 `path:"id"`
	Status  int32 `json:"status"`
}

type UpdateRoleReq struct {
	Id          int64  `path:"id"`
	Name        string `json:"name"`
	Description string `json:"description,optional"`
	Status      int32  `json:"status,optional,default=1"`
}

type UpdateUserRoleReq struct {
	UserId int64 `path:"id"`
	Role   int32 `json:"role"`
}

type UpdateUserStatusReq struct {
	UserId int64 `path:"id"`
	Status int32 `json:"status"`
}

type UpdateZoneReq struct {
	Zone string `json:"zone" validate:"required"`
}

type UserItemAdmin struct {
	Id                int64  `json:"id"`
	Username          string `json:"username"`
	Email             string `json:"email"`
	Nickname          string `json:"nickname"`
	Role              int32  `json:"role"`
	ContributionScore string `json:"contribution_score"`
	Status            int32  `json:"status"`
	CreatedAt         int64  `json:"created_at"`
}
