// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: proto/paper.proto

package paper

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SubmitPaperReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	TitleEn       string                 `protobuf:"bytes,2,opt,name=title_en,json=titleEn,proto3" json:"title_en,omitempty"`
	Abstract      string                 `protobuf:"bytes,3,opt,name=abstract,proto3" json:"abstract,omitempty"`
	AbstractEn    string                 `protobuf:"bytes,4,opt,name=abstract_en,json=abstractEn,proto3" json:"abstract_en,omitempty"`
	Content       string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	AuthorId      int64                  `protobuf:"varint,6,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	AuthorName    string                 `protobuf:"bytes,7,opt,name=author_name,json=authorName,proto3" json:"author_name,omitempty"`
	Discipline    string                 `protobuf:"bytes,8,opt,name=discipline,proto3" json:"discipline,omitempty"` // science, humanities, information, technology, other
	Keywords      string                 `protobuf:"bytes,9,opt,name=keywords,proto3" json:"keywords,omitempty"`
	FilePath      string                 `protobuf:"bytes,10,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitPaperReq) Reset() {
	*x = SubmitPaperReq{}
	mi := &file_proto_paper_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitPaperReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitPaperReq) ProtoMessage() {}

func (x *SubmitPaperReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paper_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitPaperReq.ProtoReflect.Descriptor instead.
func (*SubmitPaperReq) Descriptor() ([]byte, []int) {
	return file_proto_paper_proto_rawDescGZIP(), []int{0}
}

func (x *SubmitPaperReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SubmitPaperReq) GetTitleEn() string {
	if x != nil {
		return x.TitleEn
	}
	return ""
}

func (x *SubmitPaperReq) GetAbstract() string {
	if x != nil {
		return x.Abstract
	}
	return ""
}

func (x *SubmitPaperReq) GetAbstractEn() string {
	if x != nil {
		return x.AbstractEn
	}
	return ""
}

func (x *SubmitPaperReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SubmitPaperReq) GetAuthorId() int64 {
	if x != nil {
		return x.AuthorId
	}
	return 0
}

func (x *SubmitPaperReq) GetAuthorName() string {
	if x != nil {
		return x.AuthorName
	}
	return ""
}

func (x *SubmitPaperReq) GetDiscipline() string {
	if x != nil {
		return x.Discipline
	}
	return ""
}

func (x *SubmitPaperReq) GetKeywords() string {
	if x != nil {
		return x.Keywords
	}
	return ""
}

func (x *SubmitPaperReq) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

type PaperItem struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title            string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	TitleEn          string                 `protobuf:"bytes,3,opt,name=title_en,json=titleEn,proto3" json:"title_en,omitempty"`
	Abstract         string                 `protobuf:"bytes,4,opt,name=abstract,proto3" json:"abstract,omitempty"`
	AbstractEn       string                 `protobuf:"bytes,5,opt,name=abstract_en,json=abstractEn,proto3" json:"abstract_en,omitempty"`
	Content          string                 `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`
	AuthorId         int64                  `protobuf:"varint,7,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	AuthorName       string                 `protobuf:"bytes,8,opt,name=author_name,json=authorName,proto3" json:"author_name,omitempty"`
	Discipline       string                 `protobuf:"bytes,9,opt,name=discipline,proto3" json:"discipline,omitempty"`
	Zone             string                 `protobuf:"bytes,10,opt,name=zone,proto3" json:"zone,omitempty"` // latrine, septic_tank, stone, sediment
	ShitScore        float64                `protobuf:"fixed64,11,opt,name=shit_score,json=shitScore,proto3" json:"shit_score,omitempty"`
	AvgRating        float64                `protobuf:"fixed64,12,opt,name=avg_rating,json=avgRating,proto3" json:"avg_rating,omitempty"`
	RatingCount      int32                  `protobuf:"varint,13,opt,name=rating_count,json=ratingCount,proto3" json:"rating_count,omitempty"`
	ViewCount        int32                  `protobuf:"varint,14,opt,name=view_count,json=viewCount,proto3" json:"view_count,omitempty"`
	ControversyIndex float64                `protobuf:"fixed64,15,opt,name=controversy_index,json=controversyIndex,proto3" json:"controversy_index,omitempty"`
	Doi              string                 `protobuf:"bytes,16,opt,name=doi,proto3" json:"doi,omitempty"`
	Keywords         string                 `protobuf:"bytes,17,opt,name=keywords,proto3" json:"keywords,omitempty"`
	FilePath         string                 `protobuf:"bytes,18,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	CreatedAt        int64                  `protobuf:"varint,19,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	PromotedAt       int64                  `protobuf:"varint,20,opt,name=promoted_at,json=promotedAt,proto3" json:"promoted_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PaperItem) Reset() {
	*x = PaperItem{}
	mi := &file_proto_paper_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaperItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaperItem) ProtoMessage() {}

func (x *PaperItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paper_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaperItem.ProtoReflect.Descriptor instead.
func (*PaperItem) Descriptor() ([]byte, []int) {
	return file_proto_paper_proto_rawDescGZIP(), []int{1}
}

func (x *PaperItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PaperItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *PaperItem) GetTitleEn() string {
	if x != nil {
		return x.TitleEn
	}
	return ""
}

func (x *PaperItem) GetAbstract() string {
	if x != nil {
		return x.Abstract
	}
	return ""
}

func (x *PaperItem) GetAbstractEn() string {
	if x != nil {
		return x.AbstractEn
	}
	return ""
}

func (x *PaperItem) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *PaperItem) GetAuthorId() int64 {
	if x != nil {
		return x.AuthorId
	}
	return 0
}

func (x *PaperItem) GetAuthorName() string {
	if x != nil {
		return x.AuthorName
	}
	return ""
}

func (x *PaperItem) GetDiscipline() string {
	if x != nil {
		return x.Discipline
	}
	return ""
}

func (x *PaperItem) GetZone() string {
	if x != nil {
		return x.Zone
	}
	return ""
}

func (x *PaperItem) GetShitScore() float64 {
	if x != nil {
		return x.ShitScore
	}
	return 0
}

func (x *PaperItem) GetAvgRating() float64 {
	if x != nil {
		return x.AvgRating
	}
	return 0
}

func (x *PaperItem) GetRatingCount() int32 {
	if x != nil {
		return x.RatingCount
	}
	return 0
}

func (x *PaperItem) GetViewCount() int32 {
	if x != nil {
		return x.ViewCount
	}
	return 0
}

func (x *PaperItem) GetControversyIndex() float64 {
	if x != nil {
		return x.ControversyIndex
	}
	return 0
}

func (x *PaperItem) GetDoi() string {
	if x != nil {
		return x.Doi
	}
	return ""
}

func (x *PaperItem) GetKeywords() string {
	if x != nil {
		return x.Keywords
	}
	return ""
}

func (x *PaperItem) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *PaperItem) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *PaperItem) GetPromotedAt() int64 {
	if x != nil {
		return x.PromotedAt
	}
	return 0
}

type ListPapersReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Zone          string                 `protobuf:"bytes,1,opt,name=zone,proto3" json:"zone,omitempty"`
	Discipline    string                 `protobuf:"bytes,2,opt,name=discipline,proto3" json:"discipline,omitempty"`
	Sort          string                 `protobuf:"bytes,3,opt,name=sort,proto3" json:"sort,omitempty"` // highest_rated, most_rated, newest
	Page          int32                  `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,5,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPapersReq) Reset() {
	*x = ListPapersReq{}
	mi := &file_proto_paper_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPapersReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPapersReq) ProtoMessage() {}

func (x *ListPapersReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paper_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPapersReq.ProtoReflect.Descriptor instead.
func (*ListPapersReq) Descriptor() ([]byte, []int) {
	return file_proto_paper_proto_rawDescGZIP(), []int{2}
}

func (x *ListPapersReq) GetZone() string {
	if x != nil {
		return x.Zone
	}
	return ""
}

func (x *ListPapersReq) GetDiscipline() string {
	if x != nil {
		return x.Discipline
	}
	return ""
}

func (x *ListPapersReq) GetSort() string {
	if x != nil {
		return x.Sort
	}
	return ""
}

func (x *ListPapersReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListPapersReq) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListPapersResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*PaperItem           `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPapersResp) Reset() {
	*x = ListPapersResp{}
	mi := &file_proto_paper_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPapersResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPapersResp) ProtoMessage() {}

func (x *ListPapersResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paper_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPapersResp.ProtoReflect.Descriptor instead.
func (*ListPapersResp) Descriptor() ([]byte, []int) {
	return file_proto_paper_proto_rawDescGZIP(), []int{3}
}

func (x *ListPapersResp) GetItems() []*PaperItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListPapersResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GetPaperReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaperReq) Reset() {
	*x = GetPaperReq{}
	mi := &file_proto_paper_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaperReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaperReq) ProtoMessage() {}

func (x *GetPaperReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paper_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaperReq.ProtoReflect.Descriptor instead.
func (*GetPaperReq) Descriptor() ([]byte, []int) {
	return file_proto_paper_proto_rawDescGZIP(), []int{4}
}

func (x *GetPaperReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetPaperResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Paper         *PaperItem             `protobuf:"bytes,1,opt,name=paper,proto3" json:"paper,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaperResp) Reset() {
	*x = GetPaperResp{}
	mi := &file_proto_paper_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaperResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaperResp) ProtoMessage() {}

func (x *GetPaperResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paper_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaperResp.ProtoReflect.Descriptor instead.
func (*GetPaperResp) Descriptor() ([]byte, []int) {
	return file_proto_paper_proto_rawDescGZIP(), []int{5}
}

func (x *GetPaperResp) GetPaper() *PaperItem {
	if x != nil {
		return x.Paper
	}
	return nil
}

type SubmitPaperResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Doi           string                 `protobuf:"bytes,2,opt,name=doi,proto3" json:"doi,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitPaperResp) Reset() {
	*x = SubmitPaperResp{}
	mi := &file_proto_paper_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitPaperResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitPaperResp) ProtoMessage() {}

func (x *SubmitPaperResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paper_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitPaperResp.ProtoReflect.Descriptor instead.
func (*SubmitPaperResp) Descriptor() ([]byte, []int) {
	return file_proto_paper_proto_rawDescGZIP(), []int{6}
}

func (x *SubmitPaperResp) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SubmitPaperResp) GetDoi() string {
	if x != nil {
		return x.Doi
	}
	return ""
}

type UpdateZoneReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Zone          string                 `protobuf:"bytes,2,opt,name=zone,proto3" json:"zone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateZoneReq) Reset() {
	*x = UpdateZoneReq{}
	mi := &file_proto_paper_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateZoneReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateZoneReq) ProtoMessage() {}

func (x *UpdateZoneReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paper_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateZoneReq.ProtoReflect.Descriptor instead.
func (*UpdateZoneReq) Descriptor() ([]byte, []int) {
	return file_proto_paper_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateZoneReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateZoneReq) GetZone() string {
	if x != nil {
		return x.Zone
	}
	return ""
}

type SearchPapersReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Discipline    string                 `protobuf:"bytes,2,opt,name=discipline,proto3" json:"discipline,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchPapersReq) Reset() {
	*x = SearchPapersReq{}
	mi := &file_proto_paper_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchPapersReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchPapersReq) ProtoMessage() {}

func (x *SearchPapersReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paper_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchPapersReq.ProtoReflect.Descriptor instead.
func (*SearchPapersReq) Descriptor() ([]byte, []int) {
	return file_proto_paper_proto_rawDescGZIP(), []int{8}
}

func (x *SearchPapersReq) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchPapersReq) GetDiscipline() string {
	if x != nil {
		return x.Discipline
	}
	return ""
}

func (x *SearchPapersReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SearchPapersReq) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type UserPapersReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthorId      int64                  `protobuf:"varint,1,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserPapersReq) Reset() {
	*x = UserPapersReq{}
	mi := &file_proto_paper_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserPapersReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserPapersReq) ProtoMessage() {}

func (x *UserPapersReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paper_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserPapersReq.ProtoReflect.Descriptor instead.
func (*UserPapersReq) Descriptor() ([]byte, []int) {
	return file_proto_paper_proto_rawDescGZIP(), []int{9}
}

func (x *UserPapersReq) GetAuthorId() int64 {
	if x != nil {
		return x.AuthorId
	}
	return 0
}

func (x *UserPapersReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *UserPapersReq) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type CommonResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommonResp) Reset() {
	*x = CommonResp{}
	mi := &file_proto_paper_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommonResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonResp) ProtoMessage() {}

func (x *CommonResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paper_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonResp.ProtoReflect.Descriptor instead.
func (*CommonResp) Descriptor() ([]byte, []int) {
	return file_proto_paper_proto_rawDescGZIP(), []int{10}
}

func (x *CommonResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CommonResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_paper_proto protoreflect.FileDescriptor

const file_proto_paper_proto_rawDesc = "" +
	"\n" +
	"\x11proto/paper.proto\x12\x05paper\"\xaf\x02\n" +
	"\x0eSubmitPaperReq\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x19\n" +
	"\btitle_en\x18\x02 \x01(\tR\atitleEn\x12\x1a\n" +
	"\babstract\x18\x03 \x01(\tR\babstract\x12\x1f\n" +
	"\vabstract_en\x18\x04 \x01(\tR\n" +
	"abstractEn\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\x12\x1b\n" +
	"\tauthor_id\x18\x06 \x01(\x03R\bauthorId\x12\x1f\n" +
	"\vauthor_name\x18\a \x01(\tR\n" +
	"authorName\x12\x1e\n" +
	"\n" +
	"discipline\x18\b \x01(\tR\n" +
	"discipline\x12\x1a\n" +
	"\bkeywords\x18\t \x01(\tR\bkeywords\x12\x1b\n" +
	"\tfile_path\x18\n" +
	" \x01(\tR\bfilePath\"\xcd\x04\n" +
	"\tPaperItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x19\n" +
	"\btitle_en\x18\x03 \x01(\tR\atitleEn\x12\x1a\n" +
	"\babstract\x18\x04 \x01(\tR\babstract\x12\x1f\n" +
	"\vabstract_en\x18\x05 \x01(\tR\n" +
	"abstractEn\x12\x18\n" +
	"\acontent\x18\x06 \x01(\tR\acontent\x12\x1b\n" +
	"\tauthor_id\x18\a \x01(\x03R\bauthorId\x12\x1f\n" +
	"\vauthor_name\x18\b \x01(\tR\n" +
	"authorName\x12\x1e\n" +
	"\n" +
	"discipline\x18\t \x01(\tR\n" +
	"discipline\x12\x12\n" +
	"\x04zone\x18\n" +
	" \x01(\tR\x04zone\x12\x1d\n" +
	"\n" +
	"shit_score\x18\v \x01(\x01R\tshitScore\x12\x1d\n" +
	"\n" +
	"avg_rating\x18\f \x01(\x01R\tavgRating\x12!\n" +
	"\frating_count\x18\r \x01(\x05R\vratingCount\x12\x1d\n" +
	"\n" +
	"view_count\x18\x0e \x01(\x05R\tviewCount\x12+\n" +
	"\x11controversy_index\x18\x0f \x01(\x01R\x10controversyIndex\x12\x10\n" +
	"\x03doi\x18\x10 \x01(\tR\x03doi\x12\x1a\n" +
	"\bkeywords\x18\x11 \x01(\tR\bkeywords\x12\x1b\n" +
	"\tfile_path\x18\x12 \x01(\tR\bfilePath\x12\x1d\n" +
	"\n" +
	"created_at\x18\x13 \x01(\x03R\tcreatedAt\x12\x1f\n" +
	"\vpromoted_at\x18\x14 \x01(\x03R\n" +
	"promotedAt\"\x88\x01\n" +
	"\rListPapersReq\x12\x12\n" +
	"\x04zone\x18\x01 \x01(\tR\x04zone\x12\x1e\n" +
	"\n" +
	"discipline\x18\x02 \x01(\tR\n" +
	"discipline\x12\x12\n" +
	"\x04sort\x18\x03 \x01(\tR\x04sort\x12\x12\n" +
	"\x04page\x18\x04 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x05 \x01(\x05R\bpageSize\"N\n" +
	"\x0eListPapersResp\x12&\n" +
	"\x05items\x18\x01 \x03(\v2\x10.paper.PaperItemR\x05items\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"\x1d\n" +
	"\vGetPaperReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"6\n" +
	"\fGetPaperResp\x12&\n" +
	"\x05paper\x18\x01 \x01(\v2\x10.paper.PaperItemR\x05paper\"3\n" +
	"\x0fSubmitPaperResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x10\n" +
	"\x03doi\x18\x02 \x01(\tR\x03doi\"3\n" +
	"\rUpdateZoneReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04zone\x18\x02 \x01(\tR\x04zone\"x\n" +
	"\x0fSearchPapersReq\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x1e\n" +
	"\n" +
	"discipline\x18\x02 \x01(\tR\n" +
	"discipline\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"]\n" +
	"\rUserPapersReq\x12\x1b\n" +
	"\tauthor_id\x18\x01 \x01(\x03R\bauthorId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"@\n" +
	"\n" +
	"CommonResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\x9e\x03\n" +
	"\x05Paper\x12<\n" +
	"\vSubmitPaper\x12\x15.paper.SubmitPaperReq\x1a\x16.paper.SubmitPaperResp\x123\n" +
	"\bGetPaper\x12\x12.paper.GetPaperReq\x1a\x13.paper.GetPaperResp\x129\n" +
	"\n" +
	"ListPapers\x12\x14.paper.ListPapersReq\x1a\x15.paper.ListPapersResp\x12=\n" +
	"\fSearchPapers\x12\x16.paper.SearchPapersReq\x1a\x15.paper.ListPapersResp\x125\n" +
	"\n" +
	"UpdateZone\x12\x14.paper.UpdateZoneReq\x1a\x11.paper.CommonResp\x129\n" +
	"\n" +
	"UserPapers\x12\x14.paper.UserPapersReq\x1a\x15.paper.ListPapersResp\x126\n" +
	"\rIncrViewCount\x12\x12.paper.GetPaperReq\x1a\x11.paper.CommonRespB\tZ\a./paperb\x06proto3"

var (
	file_proto_paper_proto_rawDescOnce sync.Once
	file_proto_paper_proto_rawDescData []byte
)

func file_proto_paper_proto_rawDescGZIP() []byte {
	file_proto_paper_proto_rawDescOnce.Do(func() {
		file_proto_paper_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_paper_proto_rawDesc), len(file_proto_paper_proto_rawDesc)))
	})
	return file_proto_paper_proto_rawDescData
}

var file_proto_paper_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_paper_proto_goTypes = []any{
	(*SubmitPaperReq)(nil),  // 0: paper.SubmitPaperReq
	(*PaperItem)(nil),       // 1: paper.PaperItem
	(*ListPapersReq)(nil),   // 2: paper.ListPapersReq
	(*ListPapersResp)(nil),  // 3: paper.ListPapersResp
	(*GetPaperReq)(nil),     // 4: paper.GetPaperReq
	(*GetPaperResp)(nil),    // 5: paper.GetPaperResp
	(*SubmitPaperResp)(nil), // 6: paper.SubmitPaperResp
	(*UpdateZoneReq)(nil),   // 7: paper.UpdateZoneReq
	(*SearchPapersReq)(nil), // 8: paper.SearchPapersReq
	(*UserPapersReq)(nil),   // 9: paper.UserPapersReq
	(*CommonResp)(nil),      // 10: paper.CommonResp
}
var file_proto_paper_proto_depIdxs = []int32{
	1,  // 0: paper.ListPapersResp.items:type_name -> paper.PaperItem
	1,  // 1: paper.GetPaperResp.paper:type_name -> paper.PaperItem
	0,  // 2: paper.Paper.SubmitPaper:input_type -> paper.SubmitPaperReq
	4,  // 3: paper.Paper.GetPaper:input_type -> paper.GetPaperReq
	2,  // 4: paper.Paper.ListPapers:input_type -> paper.ListPapersReq
	8,  // 5: paper.Paper.SearchPapers:input_type -> paper.SearchPapersReq
	7,  // 6: paper.Paper.UpdateZone:input_type -> paper.UpdateZoneReq
	9,  // 7: paper.Paper.UserPapers:input_type -> paper.UserPapersReq
	4,  // 8: paper.Paper.IncrViewCount:input_type -> paper.GetPaperReq
	6,  // 9: paper.Paper.SubmitPaper:output_type -> paper.SubmitPaperResp
	5,  // 10: paper.Paper.GetPaper:output_type -> paper.GetPaperResp
	3,  // 11: paper.Paper.ListPapers:output_type -> paper.ListPapersResp
	3,  // 12: paper.Paper.SearchPapers:output_type -> paper.ListPapersResp
	10, // 13: paper.Paper.UpdateZone:output_type -> paper.CommonResp
	3,  // 14: paper.Paper.UserPapers:output_type -> paper.ListPapersResp
	10, // 15: paper.Paper.IncrViewCount:output_type -> paper.CommonResp
	9,  // [9:16] is the sub-list for method output_type
	2,  // [2:9] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_proto_paper_proto_init() }
func file_proto_paper_proto_init() {
	if File_proto_paper_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_paper_proto_rawDesc), len(file_proto_paper_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_paper_proto_goTypes,
		DependencyIndexes: file_proto_paper_proto_depIdxs,
		MessageInfos:      file_proto_paper_proto_msgTypes,
	}.Build()
	File_proto_paper_proto = out.File
	file_proto_paper_proto_goTypes = nil
	file_proto_paper_proto_depIdxs = nil
}
