// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: proto/paper.proto

package paper

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Paper_SubmitPaper_FullMethodName   = "/paper.Paper/SubmitPaper"
	Paper_GetPaper_FullMethodName      = "/paper.Paper/GetPaper"
	Paper_ListPapers_FullMethodName    = "/paper.Paper/ListPapers"
	Paper_SearchPapers_FullMethodName  = "/paper.Paper/SearchPapers"
	Paper_UpdateZone_FullMethodName    = "/paper.Paper/UpdateZone"
	Paper_UserPapers_FullMethodName    = "/paper.Paper/UserPapers"
	Paper_IncrViewCount_FullMethodName = "/paper.Paper/IncrViewCount"
)

// PaperClient is the client API for Paper service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PaperClient interface {
	SubmitPaper(ctx context.Context, in *SubmitPaperReq, opts ...grpc.CallOption) (*SubmitPaperResp, error)
	GetPaper(ctx context.Context, in *GetPaperReq, opts ...grpc.CallOption) (*GetPaperResp, error)
	ListPapers(ctx context.Context, in *ListPapersReq, opts ...grpc.CallOption) (*ListPapersResp, error)
	SearchPapers(ctx context.Context, in *SearchPapersReq, opts ...grpc.CallOption) (*SearchPapersResp, error)
	UpdateZone(ctx context.Context, in *UpdateZoneReq, opts ...grpc.CallOption) (*CommonResp, error)
	UserPapers(ctx context.Context, in *UserPapersReq, opts ...grpc.CallOption) (*ListPapersResp, error)
	IncrViewCount(ctx context.Context, in *GetPaperReq, opts ...grpc.CallOption) (*CommonResp, error)
}

type paperClient struct {
	cc grpc.ClientConnInterface
}

func NewPaperClient(cc grpc.ClientConnInterface) PaperClient {
	return &paperClient{cc}
}

func (c *paperClient) SubmitPaper(ctx context.Context, in *SubmitPaperReq, opts ...grpc.CallOption) (*SubmitPaperResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitPaperResp)
	err := c.cc.Invoke(ctx, Paper_SubmitPaper_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paperClient) GetPaper(ctx context.Context, in *GetPaperReq, opts ...grpc.CallOption) (*GetPaperResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPaperResp)
	err := c.cc.Invoke(ctx, Paper_GetPaper_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paperClient) ListPapers(ctx context.Context, in *ListPapersReq, opts ...grpc.CallOption) (*ListPapersResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPapersResp)
	err := c.cc.Invoke(ctx, Paper_ListPapers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paperClient) SearchPapers(ctx context.Context, in *SearchPapersReq, opts ...grpc.CallOption) (*SearchPapersResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchPapersResp)
	err := c.cc.Invoke(ctx, Paper_SearchPapers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paperClient) UpdateZone(ctx context.Context, in *UpdateZoneReq, opts ...grpc.CallOption) (*CommonResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResp)
	err := c.cc.Invoke(ctx, Paper_UpdateZone_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paperClient) UserPapers(ctx context.Context, in *UserPapersReq, opts ...grpc.CallOption) (*ListPapersResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPapersResp)
	err := c.cc.Invoke(ctx, Paper_UserPapers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paperClient) IncrViewCount(ctx context.Context, in *GetPaperReq, opts ...grpc.CallOption) (*CommonResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResp)
	err := c.cc.Invoke(ctx, Paper_IncrViewCount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PaperServer is the server API for Paper service.
// All implementations must embed UnimplementedPaperServer
// for forward compatibility.
type PaperServer interface {
	SubmitPaper(context.Context, *SubmitPaperReq) (*SubmitPaperResp, error)
	GetPaper(context.Context, *GetPaperReq) (*GetPaperResp, error)
	ListPapers(context.Context, *ListPapersReq) (*ListPapersResp, error)
	SearchPapers(context.Context, *SearchPapersReq) (*SearchPapersResp, error)
	UpdateZone(context.Context, *UpdateZoneReq) (*CommonResp, error)
	UserPapers(context.Context, *UserPapersReq) (*ListPapersResp, error)
	IncrViewCount(context.Context, *GetPaperReq) (*CommonResp, error)
	mustEmbedUnimplementedPaperServer()
}

// UnimplementedPaperServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPaperServer struct{}

func (UnimplementedPaperServer) SubmitPaper(context.Context, *SubmitPaperReq) (*SubmitPaperResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitPaper not implemented")
}
func (UnimplementedPaperServer) GetPaper(context.Context, *GetPaperReq) (*GetPaperResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPaper not implemented")
}
func (UnimplementedPaperServer) ListPapers(context.Context, *ListPapersReq) (*ListPapersResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPapers not implemented")
}
func (UnimplementedPaperServer) SearchPapers(context.Context, *SearchPapersReq) (*SearchPapersResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchPapers not implemented")
}
func (UnimplementedPaperServer) UpdateZone(context.Context, *UpdateZoneReq) (*CommonResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateZone not implemented")
}
func (UnimplementedPaperServer) UserPapers(context.Context, *UserPapersReq) (*ListPapersResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserPapers not implemented")
}
func (UnimplementedPaperServer) IncrViewCount(context.Context, *GetPaperReq) (*CommonResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IncrViewCount not implemented")
}
func (UnimplementedPaperServer) mustEmbedUnimplementedPaperServer() {}
func (UnimplementedPaperServer) testEmbeddedByValue()               {}

// UnsafePaperServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PaperServer will
// result in compilation errors.
type UnsafePaperServer interface {
	mustEmbedUnimplementedPaperServer()
}

func RegisterPaperServer(s grpc.ServiceRegistrar, srv PaperServer) {
	// If the following call pancis, it indicates UnimplementedPaperServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Paper_ServiceDesc, srv)
}

func _Paper_SubmitPaper_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitPaperReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaperServer).SubmitPaper(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Paper_SubmitPaper_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaperServer).SubmitPaper(ctx, req.(*SubmitPaperReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Paper_GetPaper_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPaperReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaperServer).GetPaper(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Paper_GetPaper_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaperServer).GetPaper(ctx, req.(*GetPaperReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Paper_ListPapers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPapersReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaperServer).ListPapers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Paper_ListPapers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaperServer).ListPapers(ctx, req.(*ListPapersReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Paper_SearchPapers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchPapersReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaperServer).SearchPapers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Paper_SearchPapers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaperServer).SearchPapers(ctx, req.(*SearchPapersReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Paper_UpdateZone_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateZoneReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaperServer).UpdateZone(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Paper_UpdateZone_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaperServer).UpdateZone(ctx, req.(*UpdateZoneReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Paper_UserPapers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserPapersReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaperServer).UserPapers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Paper_UserPapers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaperServer).UserPapers(ctx, req.(*UserPapersReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Paper_IncrViewCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPaperReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaperServer).IncrViewCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Paper_IncrViewCount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaperServer).IncrViewCount(ctx, req.(*GetPaperReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Paper_ServiceDesc is the grpc.ServiceDesc for Paper service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Paper_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "paper.Paper",
	HandlerType: (*PaperServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitPaper",
			Handler:    _Paper_SubmitPaper_Handler,
		},
		{
			MethodName: "GetPaper",
			Handler:    _Paper_GetPaper_Handler,
		},
		{
			MethodName: "ListPapers",
			Handler:    _Paper_ListPapers_Handler,
		},
		{
			MethodName: "SearchPapers",
			Handler:    _Paper_SearchPapers_Handler,
		},
		{
			MethodName: "UpdateZone",
			Handler:    _Paper_UpdateZone_Handler,
		},
		{
			MethodName: "UserPapers",
			Handler:    _Paper_UserPapers_Handler,
		},
		{
			MethodName: "IncrViewCount",
			Handler:    _Paper_IncrViewCount_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/paper.proto",
}
