// Code generated by goctl. Safe to edit.
// goctl 1.9.2
// Source: admin.proto

package server

import (
	"context"

	"journal/rpc/admin/admin"
	"journal/rpc/admin/internal/logic"
	"journal/rpc/admin/internal/svc"
)

type AdminServer struct {
	svcCtx *svc.ServiceContext
	admin.UnimplementedAdminServer
}

func NewAdminServer(svcCtx *svc.ServiceContext) *AdminServer {
	return &AdminServer{
		svcCtx: svcCtx,
	}
}

// User
func (s *AdminServer) ListUsers(ctx context.Context, in *admin.ListUsersReq) (*admin.ListUsersResp, error) {
	l := logic.NewListUsersLogic(ctx, s.svcCtx)
	return l.ListUsers(in)
}

func (s *AdminServer) UpdateUserRole(ctx context.Context, in *admin.UpdateUserRoleReq) (*admin.CommonResp, error) {
	l := logic.NewUpdateUserRoleLogic(ctx, s.svcCtx)
	return l.UpdateUserRole(in)
}

func (s *AdminServer) UpdateUserStatus(ctx context.Context, in *admin.UpdateUserStatusReq) (*admin.CommonResp, error) {
	l := logic.NewUpdateUserStatusLogic(ctx, s.svcCtx)
	return l.UpdateUserStatus(in)
}

// Paper
func (s *AdminServer) ListPapers(ctx context.Context, in *admin.ListPapersReq) (*admin.ListPapersResp, error) {
	l := logic.NewListPapersLogic(ctx, s.svcCtx)
	return l.ListPapers(in)
}

func (s *AdminServer) UpdatePaperStatus(ctx context.Context, in *admin.UpdatePaperStatusReq) (*admin.CommonResp, error) {
	l := logic.NewUpdatePaperStatusLogic(ctx, s.svcCtx)
	return l.UpdatePaperStatus(in)
}

func (s *AdminServer) UpdatePaperZone(ctx context.Context, in *admin.UpdatePaperZoneReq) (*admin.CommonResp, error) {
	l := logic.NewUpdatePaperZoneLogic(ctx, s.svcCtx)
	return l.UpdatePaperZone(in)
}

// Flag
func (s *AdminServer) ListFlags(ctx context.Context, in *admin.ListFlagsReq) (*admin.ListFlagsResp, error) {
	l := logic.NewListFlagsLogic(ctx, s.svcCtx)
	return l.ListFlags(in)
}

func (s *AdminServer) ResolveFlag(ctx context.Context, in *admin.ResolveFlagReq) (*admin.CommonResp, error) {
	l := logic.NewResolveFlagLogic(ctx, s.svcCtx)
	return l.ResolveFlag(in)
}

// Audit
func (s *AdminServer) RecordAuditLog(ctx context.Context, in *admin.RecordAuditLogReq) (*admin.CommonResp, error) {
	l := logic.NewRecordAuditLogLogic(ctx, s.svcCtx)
	return l.RecordAuditLog(in)
}

func (s *AdminServer) ListAuditLogs(ctx context.Context, in *admin.ListAuditLogsReq) (*admin.ListAuditLogsResp, error) {
	l := logic.NewListAuditLogsLogic(ctx, s.svcCtx)
	return l.ListAuditLogs(in)
}

// RBAC - Role
func (s *AdminServer) ListRoles(ctx context.Context, in *admin.ListRolesReq) (*admin.ListRolesResp, error) {
	l := logic.NewListRolesLogic(ctx, s.svcCtx)
	return l.ListRoles(in)
}

func (s *AdminServer) CreateRole(ctx context.Context, in *admin.CreateRoleReq) (*admin.CreateRoleResp, error) {
	l := logic.NewCreateRoleLogic(ctx, s.svcCtx)
	return l.CreateRole(in)
}

func (s *AdminServer) UpdateRole(ctx context.Context, in *admin.UpdateRoleReq) (*admin.CommonResp, error) {
	l := logic.NewUpdateRoleLogic(ctx, s.svcCtx)
	return l.UpdateRole(in)
}

func (s *AdminServer) DeleteRole(ctx context.Context, in *admin.DeleteRoleReq) (*admin.CommonResp, error) {
	l := logic.NewDeleteRoleLogic(ctx, s.svcCtx)
	return l.DeleteRole(in)
}

// RBAC - Permission
func (s *AdminServer) ListPermissions(ctx context.Context, in *admin.ListPermissionsReq) (*admin.ListPermissionsResp, error) {
	l := logic.NewListPermissionsLogic(ctx, s.svcCtx)
	return l.ListPermissions(in)
}

// RBAC - Role-Permission
func (s *AdminServer) GetRolePermissions(ctx context.Context, in *admin.GetRolePermissionsReq) (*admin.GetRolePermissionsResp, error) {
	l := logic.NewGetRolePermissionsLogic(ctx, s.svcCtx)
	return l.GetRolePermissions(in)
}

func (s *AdminServer) SetRolePermissions(ctx context.Context, in *admin.SetRolePermissionsReq) (*admin.CommonResp, error) {
	l := logic.NewSetRolePermissionsLogic(ctx, s.svcCtx)
	return l.SetRolePermissions(in)
}

// RBAC - User-Role
func (s *AdminServer) ListUserRoles(ctx context.Context, in *admin.ListUserRolesReq) (*admin.ListUserRolesResp, error) {
	l := logic.NewListUserRolesLogic(ctx, s.svcCtx)
	return l.ListUserRoles(in)
}

func (s *AdminServer) AssignUserRole(ctx context.Context, in *admin.AssignUserRoleReq) (*admin.CommonResp, error) {
	l := logic.NewAssignUserRoleLogic(ctx, s.svcCtx)
	return l.AssignUserRole(in)
}

func (s *AdminServer) RevokeUserRole(ctx context.Context, in *admin.RevokeUserRoleReq) (*admin.CommonResp, error) {
	l := logic.NewRevokeUserRoleLogic(ctx, s.svcCtx)
	return l.RevokeUserRole(in)
}
