// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: admin.proto

package server

import (
	"context"

	"journal/rpc/admin/admin"
	"journal/rpc/admin/internal/logic"
	"journal/rpc/admin/internal/svc"
)

type AdminServer struct {
	svcCtx *svc.ServiceContext
	admin.UnimplementedAdminServer
}

func NewAdminServer(svcCtx *svc.ServiceContext) *AdminServer {
	return &AdminServer{
		svcCtx: svcCtx,
	}
}

// User
func (s *AdminServer) ListUsers(ctx context.Context, in *admin.ListUsersReq) (*admin.ListUsersResp, error) {
	l := logic.NewListUsersLogic(ctx, s.svcCtx)
	return l.ListUsers(in)
}

func (s *AdminServer) UpdateUserRole(ctx context.Context, in *admin.UpdateUserRoleReq) (*admin.CommonResp, error) {
	l := logic.NewUpdateUserRoleLogic(ctx, s.svcCtx)
	return l.UpdateUserRole(in)
}

func (s *AdminServer) UpdateUserStatus(ctx context.Context, in *admin.UpdateUserStatusReq) (*admin.CommonResp, error) {
	l := logic.NewUpdateUserStatusLogic(ctx, s.svcCtx)
	return l.UpdateUserStatus(in)
}

// Paper
func (s *AdminServer) ListPapers(ctx context.Context, in *admin.ListPapersReq) (*admin.ListPapersResp, error) {
	l := logic.NewListPapersLogic(ctx, s.svcCtx)
	return l.ListPapers(in)
}

func (s *AdminServer) UpdatePaperStatus(ctx context.Context, in *admin.UpdatePaperStatusReq) (*admin.CommonResp, error) {
	l := logic.NewUpdatePaperStatusLogic(ctx, s.svcCtx)
	return l.UpdatePaperStatus(in)
}

func (s *AdminServer) UpdatePaperZone(ctx context.Context, in *admin.UpdatePaperZoneReq) (*admin.CommonResp, error) {
	l := logic.NewUpdatePaperZoneLogic(ctx, s.svcCtx)
	return l.UpdatePaperZone(in)
}

// Flag
func (s *AdminServer) ListFlags(ctx context.Context, in *admin.ListFlagsReq) (*admin.ListFlagsResp, error) {
	l := logic.NewListFlagsLogic(ctx, s.svcCtx)
	return l.ListFlags(in)
}

func (s *AdminServer) ResolveFlag(ctx context.Context, in *admin.ResolveFlagReq) (*admin.CommonResp, error) {
	l := logic.NewResolveFlagLogic(ctx, s.svcCtx)
	return l.ResolveFlag(in)
}

// Audit
func (s *AdminServer) RecordAuditLog(ctx context.Context, in *admin.RecordAuditLogReq) (*admin.CommonResp, error) {
	l := logic.NewRecordAuditLogLogic(ctx, s.svcCtx)
	return l.RecordAuditLog(in)
}
