// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: rating.proto

package rating

import (
	"context"

	"journal/rpc/rating/rating"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	PaperRatingsReq  = rating.PaperRatingsReq
	PaperRatingsResp = rating.PaperRatingsResp
	RatePaperReq     = rating.RatePaperReq
	RateResp         = rating.RateResp
	RatingItem       = rating.RatingItem
	UserRatingsReq   = rating.UserRatingsReq
	UserRatingsResp  = rating.UserRatingsResp

	Rating interface {
		RatePaper(ctx context.Context, in *RatePaperReq, opts ...grpc.CallOption) (*RateResp, error)
		GetPaperRatings(ctx context.Context, in *PaperRatingsReq, opts ...grpc.CallOption) (*PaperRatingsResp, error)
		GetUserRatings(ctx context.Context, in *UserRatingsReq, opts ...grpc.CallOption) (*UserRatingsResp, error)
	}

	defaultRating struct {
		cli zrpc.Client
	}
)

func NewRating(cli zrpc.Client) Rating {
	return &defaultRating{
		cli: cli,
	}
}

func (m *defaultRating) RatePaper(ctx context.Context, in *RatePaperReq, opts ...grpc.CallOption) (*RateResp, error) {
	client := rating.NewRatingClient(m.cli.Conn())
	return client.RatePaper(ctx, in, opts...)
}

func (m *defaultRating) GetPaperRatings(ctx context.Context, in *PaperRatingsReq, opts ...grpc.CallOption) (*PaperRatingsResp, error) {
	client := rating.NewRatingClient(m.cli.Conn())
	return client.GetPaperRatings(ctx, in, opts...)
}

func (m *defaultRating) GetUserRatings(ctx context.Context, in *UserRatingsReq, opts ...grpc.CallOption) (*UserRatingsResp, error) {
	client := rating.NewRatingClient(m.cli.Conn())
	return client.GetUserRatings(ctx, in, opts...)
}
