// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: paper.proto

package paper

import (
	"context"

	"journal/rpc/paper/paper"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CommonResp      = paper.CommonResp
	GetPaperReq     = paper.GetPaperReq
	GetPaperResp    = paper.GetPaperResp
	ListPapersReq   = paper.ListPapersReq
	ListPapersResp  = paper.ListPapersResp
	PaperItem       = paper.PaperItem
	SearchPapersReq = paper.SearchPapersReq
	SubmitPaperReq  = paper.SubmitPaperReq
	SubmitPaperResp = paper.SubmitPaperResp
	UpdateZoneReq   = paper.UpdateZoneReq
	UserPapersReq   = paper.UserPapersReq

	Paper interface {
		SubmitPaper(ctx context.Context, in *SubmitPaperReq, opts ...grpc.CallOption) (*SubmitPaperResp, error)
		GetPaper(ctx context.Context, in *GetPaperReq, opts ...grpc.CallOption) (*GetPaperResp, error)
		ListPapers(ctx context.Context, in *ListPapersReq, opts ...grpc.CallOption) (*ListPapersResp, error)
		SearchPapers(ctx context.Context, in *SearchPapersReq, opts ...grpc.CallOption) (*ListPapersResp, error)
		UpdateZone(ctx context.Context, in *UpdateZoneReq, opts ...grpc.CallOption) (*CommonResp, error)
		UserPapers(ctx context.Context, in *UserPapersReq, opts ...grpc.CallOption) (*ListPapersResp, error)
		IncrViewCount(ctx context.Context, in *GetPaperReq, opts ...grpc.CallOption) (*CommonResp, error)
	}

	defaultPaper struct {
		cli zrpc.Client
	}
)

func NewPaper(cli zrpc.Client) Paper {
	return &defaultPaper{
		cli: cli,
	}
}

func (m *defaultPaper) SubmitPaper(ctx context.Context, in *SubmitPaperReq, opts ...grpc.CallOption) (*SubmitPaperResp, error) {
	client := paper.NewPaperClient(m.cli.Conn())
	return client.SubmitPaper(ctx, in, opts...)
}

func (m *defaultPaper) GetPaper(ctx context.Context, in *GetPaperReq, opts ...grpc.CallOption) (*GetPaperResp, error) {
	client := paper.NewPaperClient(m.cli.Conn())
	return client.GetPaper(ctx, in, opts...)
}

func (m *defaultPaper) ListPapers(ctx context.Context, in *ListPapersReq, opts ...grpc.CallOption) (*ListPapersResp, error) {
	client := paper.NewPaperClient(m.cli.Conn())
	return client.ListPapers(ctx, in, opts...)
}

func (m *defaultPaper) SearchPapers(ctx context.Context, in *SearchPapersReq, opts ...grpc.CallOption) (*ListPapersResp, error) {
	client := paper.NewPaperClient(m.cli.Conn())
	return client.SearchPapers(ctx, in, opts...)
}

func (m *defaultPaper) UpdateZone(ctx context.Context, in *UpdateZoneReq, opts ...grpc.CallOption) (*CommonResp, error) {
	client := paper.NewPaperClient(m.cli.Conn())
	return client.UpdateZone(ctx, in, opts...)
}

func (m *defaultPaper) UserPapers(ctx context.Context, in *UserPapersReq, opts ...grpc.CallOption) (*ListPapersResp, error) {
	client := paper.NewPaperClient(m.cli.Conn())
	return client.UserPapers(ctx, in, opts...)
}

func (m *defaultPaper) IncrViewCount(ctx context.Context, in *GetPaperReq, opts ...grpc.CallOption) (*CommonResp, error) {
	client := paper.NewPaperClient(m.cli.Conn())
	return client.IncrViewCount(ctx, in, opts...)
}
