// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type CommonResp struct {
	Success bool   `json:"success"`
	Message string `json:"message"`
}

type AchievementBadge struct {
	Code        string `json:"code"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Tier        string `json:"tier"`
	UnlockedAt  int64  `json:"unlocked_at"`
}

type FlagActionResp struct {
	Success bool           `json:"success"`
	Message string         `json:"message"`
	FlagId  int64          `json:"flag_id,omitempty"`
	Status  FlagStatusResp `json:"status"`
}

type FlagReq struct {
	Reason string `json:"reason" validate:"required"`
	Detail string `json:"detail,optional"`
}

type FlagStatusResp struct {
	Exists           bool    `json:"exists"`
	TargetType       string  `json:"target_type"`
	TargetId         int64   `json:"target_id"`
	FlagCount        int32   `json:"flag_count"`
	PendingCount     int32   `json:"pending_count"`
	WeightedSum      float64 `json:"weighted_sum"`
	Quorum           int32   `json:"quorum"`
	DegradationLevel int32   `json:"degradation_level"`
}

type CreateNewsReq struct {
	Title     string `json:"title" validate:"required"`
	TitleEn   string `json:"title_en,optional"`
	Content   string `json:"content" validate:"required"`
	ContentEn string `json:"content_en,optional"`
	Category  string `json:"category,optional,default=announcement"`
	IsPinned  bool   `json:"is_pinned,optional"`
}

type IdReq struct {
	Id int64 `path:"id"`
}

type IdResp struct {
	Id int64 `json:"id"`
}

type ListNewsResp struct {
	Items []NewsItem `json:"items"`
	Total int64      `json:"total"`
}

type ListPapersReq struct {
	Zone       string `form:"zone,optional"`
	Discipline string `form:"discipline,optional"`
	Sort       string `form:"sort,optional,default=newest"`
	Page       int    `form:"page,optional,default=1"`
	PageSize   int    `form:"page_size,optional,default=20"`
}

type ListPapersResp struct {
	Items []PaperItem `json:"items"`
	Total int64       `json:"total"`
}

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResp struct {
	Token    string   `json:"token"`
	ExpireAt int64    `json:"expire_at"`
	UserInfo UserInfo `json:"user_info"`
}

type NewsItem struct {
	Id        int64  `json:"id"`
	Title     string `json:"title"`
	TitleEn   string `json:"title_en"`
	Content   string `json:"content"`
	ContentEn string `json:"content_en"`
	AuthorId  int64  `json:"author_id"`
	Category  string `json:"category"`
	IsPinned  bool   `json:"is_pinned"`
	CreatedAt int64  `json:"created_at"`
}

type PageReq struct {
	Page     int `form:"page,optional,default=1"`
	PageSize int `form:"page_size,optional,default=20"`
}

type PaperItem struct {
	Id               int64   `json:"id"`
	Title            string  `json:"title"`
	TitleEn          string  `json:"title_en"`
	Abstract         string  `json:"abstract"`
	AbstractEn       string  `json:"abstract_en"`
	Content          string  `json:"content,omitempty"`
	AuthorId         int64   `json:"author_id"`
	AuthorName       string  `json:"author_name"`
	Discipline       string  `json:"discipline"`
	Zone             string  `json:"zone"`
	ShitScore        float64 `json:"shit_score"`
	AvgRating        float64 `json:"avg_rating"`
	RatingCount      int32   `json:"rating_count"`
	ViewCount        int32   `json:"view_count"`
	ControversyIndex float64 `json:"controversy_index"`
	Doi              string  `json:"doi"`
	Keywords         string  `json:"keywords"`
	FilePath         string  `json:"file_path"`
	Status           int32   `json:"status"`
	DegradationLevel int32   `json:"degradation_level"`
	CreatedAt        int64   `json:"created_at"`
	PromotedAt       int64   `json:"promoted_at"`
}

type PaperRatingsResp struct {
	Items    []RatingItem `json:"items"`
	Total    int64        `json:"total"`
	AvgScore float64      `json:"avg_score"`
}

type RatePaperReq struct {
	Score   int32  `json:"score" validate:"required,min=1,max=10"`
	Comment string `json:"comment,optional"`
}

type RatingItem struct {
	Id        int64  `json:"id"`
	PaperId   int64  `json:"paper_id"`
	UserId    int64  `json:"user_id"`
	Username  string `json:"username"`
	Nickname  string `json:"nickname"`
	Score     int32  `json:"score"`
	Comment   string `json:"comment"`
	CreatedAt int64  `json:"created_at"`
}

type RegisterReq struct {
	Username string `json:"username" validate:"required,min=3,max=32"`
	Email    string `json:"email" validate:"required,email"`
	Password string `json:"password" validate:"required,min=6"`
	Nickname string `json:"nickname,optional"`
}

type SearchPapersReq struct {
	Query           string `form:"query"`
	Discipline      string `form:"discipline,optional"`
	Sort            string `form:"sort,optional,default=relevance"`
	Engine          string `form:"engine,optional,default=auto"`
	ShadowCompare   bool   `form:"shadow_compare,optional"`
	SuggestionLimit int    `form:"suggestion_limit,optional,default=6"`
	Page            int    `form:"page,optional,default=1"`
	PageSize        int    `form:"page_size,optional,default=20"`
}

type SearchMeta struct {
	Engine         string   `json:"engine"`
	UsedFallback   bool     `json:"used_fallback"`
	FallbackReason string   `json:"fallback_reason"`
	ShadowCompared bool     `json:"shadow_compared"`
	IndexedDocs    int32    `json:"indexed_docs"`
	IndexedTerms   int32    `json:"indexed_terms"`
	IndexSignature string   `json:"index_signature"`
	ExpandedTerms  []string `json:"expanded_terms"`
}

type SearchPapersResp struct {
	Items       []PaperItem `json:"items"`
	Total       int64       `json:"total"`
	Suggestions []string    `json:"suggestions"`
	Meta        SearchMeta  `json:"meta"`
}

type PublicUserProfile struct {
	Id                int64              `json:"id"`
	Username          string             `json:"username"`
	Nickname          string             `json:"nickname"`
	Avatar            string             `json:"avatar"`
	Role              int32              `json:"role"`
	ContributionScore string             `json:"contribution_score"`
	CreatedAt         int64              `json:"created_at"`
	Achievements      []AchievementBadge `json:"achievements"`
}

type SubmitPaperReq struct {
	Title      string `json:"title" validate:"required"`
	TitleEn    string `json:"title_en,optional"`
	Abstract   string `json:"abstract" validate:"required"`
	AbstractEn string `json:"abstract_en,optional"`
	Content    string `json:"content" validate:"required"`
	Discipline string `json:"discipline" validate:"required"`
	Keywords   string `json:"keywords,optional"`
}

type SubmitPaperResp struct {
	Id  int64  `json:"id"`
	Doi string `json:"doi"`
}

type UpdateProfileReq struct {
	Nickname string `json:"nickname,optional"`
	Avatar   string `json:"avatar,optional"`
}

type UserPageReq struct {
	Id       int64 `path:"id"`
	Page     int   `form:"page,optional,default=1"`
	PageSize int   `form:"page_size,optional,default=20"`
}

type UpdateZoneReq struct {
	Zone string `json:"zone" validate:"required"`
}

type UserInfo struct {
	Id                int64              `json:"id"`
	Username          string             `json:"username"`
	Email             string             `json:"email"`
	Nickname          string             `json:"nickname"`
	Avatar            string             `json:"avatar"`
	Role              int32              `json:"role"`
	ContributionScore string             `json:"contribution_score"`
	CreatedAt         int64              `json:"created_at"`
	AdminPermissions  []string           `json:"admin_permissions"`
	Achievements      []AchievementBadge `json:"achievements"`
}

type UserRatingsResp struct {
	Items []RatingItem `json:"items"`
	Total int64        `json:"total"`
}
