// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: proto/news.proto

package news

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateNewsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	TitleEn       string                 `protobuf:"bytes,2,opt,name=title_en,json=titleEn,proto3" json:"title_en,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	ContentEn     string                 `protobuf:"bytes,4,opt,name=content_en,json=contentEn,proto3" json:"content_en,omitempty"`
	AuthorId      int64                  `protobuf:"varint,5,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	Category      string                 `protobuf:"bytes,6,opt,name=category,proto3" json:"category,omitempty"` // announcement, governance, maintenance, feature
	IsPinned      bool                   `protobuf:"varint,7,opt,name=is_pinned,json=isPinned,proto3" json:"is_pinned,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNewsReq) Reset() {
	*x = CreateNewsReq{}
	mi := &file_proto_news_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNewsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNewsReq) ProtoMessage() {}

func (x *CreateNewsReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_news_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNewsReq.ProtoReflect.Descriptor instead.
func (*CreateNewsReq) Descriptor() ([]byte, []int) {
	return file_proto_news_proto_rawDescGZIP(), []int{0}
}

func (x *CreateNewsReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateNewsReq) GetTitleEn() string {
	if x != nil {
		return x.TitleEn
	}
	return ""
}

func (x *CreateNewsReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CreateNewsReq) GetContentEn() string {
	if x != nil {
		return x.ContentEn
	}
	return ""
}

func (x *CreateNewsReq) GetAuthorId() int64 {
	if x != nil {
		return x.AuthorId
	}
	return 0
}

func (x *CreateNewsReq) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *CreateNewsReq) GetIsPinned() bool {
	if x != nil {
		return x.IsPinned
	}
	return false
}

type NewsItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	TitleEn       string                 `protobuf:"bytes,3,opt,name=title_en,json=titleEn,proto3" json:"title_en,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	ContentEn     string                 `protobuf:"bytes,5,opt,name=content_en,json=contentEn,proto3" json:"content_en,omitempty"`
	AuthorId      int64                  `protobuf:"varint,6,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	Category      string                 `protobuf:"bytes,7,opt,name=category,proto3" json:"category,omitempty"`
	IsPinned      bool                   `protobuf:"varint,8,opt,name=is_pinned,json=isPinned,proto3" json:"is_pinned,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewsItem) Reset() {
	*x = NewsItem{}
	mi := &file_proto_news_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewsItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewsItem) ProtoMessage() {}

func (x *NewsItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_news_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewsItem.ProtoReflect.Descriptor instead.
func (*NewsItem) Descriptor() ([]byte, []int) {
	return file_proto_news_proto_rawDescGZIP(), []int{1}
}

func (x *NewsItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *NewsItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *NewsItem) GetTitleEn() string {
	if x != nil {
		return x.TitleEn
	}
	return ""
}

func (x *NewsItem) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *NewsItem) GetContentEn() string {
	if x != nil {
		return x.ContentEn
	}
	return ""
}

func (x *NewsItem) GetAuthorId() int64 {
	if x != nil {
		return x.AuthorId
	}
	return 0
}

func (x *NewsItem) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *NewsItem) GetIsPinned() bool {
	if x != nil {
		return x.IsPinned
	}
	return false
}

func (x *NewsItem) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type ListNewsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Category      string                 `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNewsReq) Reset() {
	*x = ListNewsReq{}
	mi := &file_proto_news_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNewsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNewsReq) ProtoMessage() {}

func (x *ListNewsReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_news_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNewsReq.ProtoReflect.Descriptor instead.
func (*ListNewsReq) Descriptor() ([]byte, []int) {
	return file_proto_news_proto_rawDescGZIP(), []int{2}
}

func (x *ListNewsReq) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *ListNewsReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListNewsReq) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListNewsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*NewsItem            `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNewsResp) Reset() {
	*x = ListNewsResp{}
	mi := &file_proto_news_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNewsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNewsResp) ProtoMessage() {}

func (x *ListNewsResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_news_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNewsResp.ProtoReflect.Descriptor instead.
func (*ListNewsResp) Descriptor() ([]byte, []int) {
	return file_proto_news_proto_rawDescGZIP(), []int{3}
}

func (x *ListNewsResp) GetItems() []*NewsItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListNewsResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GetNewsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNewsReq) Reset() {
	*x = GetNewsReq{}
	mi := &file_proto_news_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNewsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNewsReq) ProtoMessage() {}

func (x *GetNewsReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_news_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNewsReq.ProtoReflect.Descriptor instead.
func (*GetNewsReq) Descriptor() ([]byte, []int) {
	return file_proto_news_proto_rawDescGZIP(), []int{4}
}

func (x *GetNewsReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetNewsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	News          *NewsItem              `protobuf:"bytes,1,opt,name=news,proto3" json:"news,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNewsResp) Reset() {
	*x = GetNewsResp{}
	mi := &file_proto_news_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNewsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNewsResp) ProtoMessage() {}

func (x *GetNewsResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_news_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNewsResp.ProtoReflect.Descriptor instead.
func (*GetNewsResp) Descriptor() ([]byte, []int) {
	return file_proto_news_proto_rawDescGZIP(), []int{5}
}

func (x *GetNewsResp) GetNews() *NewsItem {
	if x != nil {
		return x.News
	}
	return nil
}

type CommonResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommonResp) Reset() {
	*x = CommonResp{}
	mi := &file_proto_news_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommonResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonResp) ProtoMessage() {}

func (x *CommonResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_news_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonResp.ProtoReflect.Descriptor instead.
func (*CommonResp) Descriptor() ([]byte, []int) {
	return file_proto_news_proto_rawDescGZIP(), []int{6}
}

func (x *CommonResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CommonResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_news_proto protoreflect.FileDescriptor

const file_proto_news_proto_rawDesc = "" +
	"\n" +
	"\x10proto/news.proto\x12\x04news\"\xcf\x01\n" +
	"\rCreateNewsReq\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x19\n" +
	"\btitle_en\x18\x02 \x01(\tR\atitleEn\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x1d\n" +
	"\n" +
	"content_en\x18\x04 \x01(\tR\tcontentEn\x12\x1b\n" +
	"\tauthor_id\x18\x05 \x01(\x03R\bauthorId\x12\x1a\n" +
	"\bcategory\x18\x06 \x01(\tR\bcategory\x12\x1b\n" +
	"\tis_pinned\x18\a \x01(\bR\bisPinned\"\xf9\x01\n" +
	"\bNewsItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x19\n" +
	"\btitle_en\x18\x03 \x01(\tR\atitleEn\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x1d\n" +
	"\n" +
	"content_en\x18\x05 \x01(\tR\tcontentEn\x12\x1b\n" +
	"\tauthor_id\x18\x06 \x01(\x03R\bauthorId\x12\x1a\n" +
	"\bcategory\x18\a \x01(\tR\bcategory\x12\x1b\n" +
	"\tis_pinned\x18\b \x01(\bR\bisPinned\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\x03R\tcreatedAt\"Z\n" +
	"\vListNewsReq\x12\x1a\n" +
	"\bcategory\x18\x01 \x01(\tR\bcategory\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"J\n" +
	"\fListNewsResp\x12$\n" +
	"\x05items\x18\x01 \x03(\v2\x0e.news.NewsItemR\x05items\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"\x1c\n" +
	"\n" +
	"GetNewsReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"1\n" +
	"\vGetNewsResp\x12\"\n" +
	"\x04news\x18\x01 \x01(\v2\x0e.news.NewsItemR\x04news\"@\n" +
	"\n" +
	"CommonResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\x9e\x01\n" +
	"\x04News\x123\n" +
	"\n" +
	"CreateNews\x12\x13.news.CreateNewsReq\x1a\x10.news.CommonResp\x121\n" +
	"\bListNews\x12\x11.news.ListNewsReq\x1a\x12.news.ListNewsResp\x12.\n" +
	"\aGetNews\x12\x10.news.GetNewsReq\x1a\x11.news.GetNewsRespB\bZ\x06./newsb\x06proto3"

var (
	file_proto_news_proto_rawDescOnce sync.Once
	file_proto_news_proto_rawDescData []byte
)

func file_proto_news_proto_rawDescGZIP() []byte {
	file_proto_news_proto_rawDescOnce.Do(func() {
		file_proto_news_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_news_proto_rawDesc), len(file_proto_news_proto_rawDesc)))
	})
	return file_proto_news_proto_rawDescData
}

var file_proto_news_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_news_proto_goTypes = []any{
	(*CreateNewsReq)(nil), // 0: news.CreateNewsReq
	(*NewsItem)(nil),      // 1: news.NewsItem
	(*ListNewsReq)(nil),   // 2: news.ListNewsReq
	(*ListNewsResp)(nil),  // 3: news.ListNewsResp
	(*GetNewsReq)(nil),    // 4: news.GetNewsReq
	(*GetNewsResp)(nil),   // 5: news.GetNewsResp
	(*CommonResp)(nil),    // 6: news.CommonResp
}
var file_proto_news_proto_depIdxs = []int32{
	1, // 0: news.ListNewsResp.items:type_name -> news.NewsItem
	1, // 1: news.GetNewsResp.news:type_name -> news.NewsItem
	0, // 2: news.News.CreateNews:input_type -> news.CreateNewsReq
	2, // 3: news.News.ListNews:input_type -> news.ListNewsReq
	4, // 4: news.News.GetNews:input_type -> news.GetNewsReq
	6, // 5: news.News.CreateNews:output_type -> news.CommonResp
	3, // 6: news.News.ListNews:output_type -> news.ListNewsResp
	5, // 7: news.News.GetNews:output_type -> news.GetNewsResp
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_news_proto_init() }
func file_proto_news_proto_init() {
	if File_proto_news_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_news_proto_rawDesc), len(file_proto_news_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_news_proto_goTypes,
		DependencyIndexes: file_proto_news_proto_depIdxs,
		MessageInfos:      file_proto_news_proto_msgTypes,
	}.Build()
	File_proto_news_proto = out.File
	file_proto_news_proto_goTypes = nil
	file_proto_news_proto_depIdxs = nil
}
