apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-rpc
  namespace: journal
  labels:
    app: user-rpc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-rpc
  template:
    metadata:
      labels:
        app: user-rpc
    spec:
      containers:
        - name: user-rpc
          image: ghcr.io/b022mc/journal-user-rpc:latest
          ports:
            - containerPort: 9001
          volumeMounts:
            - name: config
              mountPath: /app/etc/user.yaml
              subPath: user.yaml
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "300m"
          readinessProbe:
            tcpSocket:
              port: 9001
            initialDelaySeconds: 10
            periodSeconds: 10
      volumes:
        - name: config
          configMap:
            name: user-rpc-config
---
apiVersion: v1
kind: Service
metadata:
  name: user-rpc
  namespace: journal
spec:
  type: ClusterIP
  selector:
    app: user-rpc
  ports:
    - port: 9001
      targetPort: 9001
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: user-rpc-config
  namespace: journal
data:
  user.yaml: |
    Name: user.rpc
    ListenOn: 0.0.0.0:9001
    Etcd:
      Hosts:
        - etcd.journal.svc.cluster.local:2379
      Key: user.rpc

    DB:
      ReadWriteSplit: false
      DataSource: "journal:banishmentB022.@tcp(mysql.journal.svc.cluster.local:3306)/journal?charset=utf8mb4&parseTime=true&loc=Asia%2FShanghai"

    JwtSecret: "journal-jwt-secret-key-2026"
    JwtExpireHrs: 72

    Telemetry:
      Name: user.rpc
      Endpoint: http://jaeger.journal.svc.cluster.local:4318
      Batcher: otlphttp

    Prometheus:
      Host: 0.0.0.0
      Port: 9101
      Path: /metrics
