// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: admin.proto

package adminClient

import (
	"context"

	"journal/rpc/admin/admin"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CommonResp           = admin.CommonResp
	FlagItem             = admin.FlagItem
	ListFlagsReq         = admin.ListFlagsReq
	ListFlagsResp        = admin.ListFlagsResp
	ListPapersReq        = admin.ListPapersReq
	ListPapersResp       = admin.ListPapersResp
	ListUsersReq         = admin.ListUsersReq
	ListUsersResp        = admin.ListUsersResp
	PaperItem            = admin.PaperItem
	RecordAuditLogReq    = admin.RecordAuditLogReq
	ResolveFlagReq       = admin.ResolveFlagReq
	UpdatePaperStatusReq = admin.UpdatePaperStatusReq
	UpdatePaperZoneReq   = admin.UpdatePaperZoneReq
	UpdateUserRoleReq    = admin.UpdateUserRoleReq
	UpdateUserStatusReq  = admin.UpdateUserStatusReq
	UserItem             = admin.UserItem

	Admin interface {
		// User
		ListUsers(ctx context.Context, in *ListUsersReq, opts ...grpc.CallOption) (*ListUsersResp, error)
		UpdateUserRole(ctx context.Context, in *UpdateUserRoleReq, opts ...grpc.CallOption) (*CommonResp, error)
		UpdateUserStatus(ctx context.Context, in *UpdateUserStatusReq, opts ...grpc.CallOption) (*CommonResp, error)
		// Paper
		ListPapers(ctx context.Context, in *ListPapersReq, opts ...grpc.CallOption) (*ListPapersResp, error)
		UpdatePaperStatus(ctx context.Context, in *UpdatePaperStatusReq, opts ...grpc.CallOption) (*CommonResp, error)
		UpdatePaperZone(ctx context.Context, in *UpdatePaperZoneReq, opts ...grpc.CallOption) (*CommonResp, error)
		// Flag
		ListFlags(ctx context.Context, in *ListFlagsReq, opts ...grpc.CallOption) (*ListFlagsResp, error)
		ResolveFlag(ctx context.Context, in *ResolveFlagReq, opts ...grpc.CallOption) (*CommonResp, error)
		// Audit
		RecordAuditLog(ctx context.Context, in *RecordAuditLogReq, opts ...grpc.CallOption) (*CommonResp, error)
	}

	defaultAdmin struct {
		cli zrpc.Client
	}
)

func NewAdmin(cli zrpc.Client) Admin {
	return &defaultAdmin{
		cli: cli,
	}
}

// User
func (m *defaultAdmin) ListUsers(ctx context.Context, in *ListUsersReq, opts ...grpc.CallOption) (*ListUsersResp, error) {
	client := admin.NewAdminClient(m.cli.Conn())
	return client.ListUsers(ctx, in, opts...)
}

func (m *defaultAdmin) UpdateUserRole(ctx context.Context, in *UpdateUserRoleReq, opts ...grpc.CallOption) (*CommonResp, error) {
	client := admin.NewAdminClient(m.cli.Conn())
	return client.UpdateUserRole(ctx, in, opts...)
}

func (m *defaultAdmin) UpdateUserStatus(ctx context.Context, in *UpdateUserStatusReq, opts ...grpc.CallOption) (*CommonResp, error) {
	client := admin.NewAdminClient(m.cli.Conn())
	return client.UpdateUserStatus(ctx, in, opts...)
}

// Paper
func (m *defaultAdmin) ListPapers(ctx context.Context, in *ListPapersReq, opts ...grpc.CallOption) (*ListPapersResp, error) {
	client := admin.NewAdminClient(m.cli.Conn())
	return client.ListPapers(ctx, in, opts...)
}

func (m *defaultAdmin) UpdatePaperStatus(ctx context.Context, in *UpdatePaperStatusReq, opts ...grpc.CallOption) (*CommonResp, error) {
	client := admin.NewAdminClient(m.cli.Conn())
	return client.UpdatePaperStatus(ctx, in, opts...)
}

func (m *defaultAdmin) UpdatePaperZone(ctx context.Context, in *UpdatePaperZoneReq, opts ...grpc.CallOption) (*CommonResp, error) {
	client := admin.NewAdminClient(m.cli.Conn())
	return client.UpdatePaperZone(ctx, in, opts...)
}

// Flag
func (m *defaultAdmin) ListFlags(ctx context.Context, in *ListFlagsReq, opts ...grpc.CallOption) (*ListFlagsResp, error) {
	client := admin.NewAdminClient(m.cli.Conn())
	return client.ListFlags(ctx, in, opts...)
}

func (m *defaultAdmin) ResolveFlag(ctx context.Context, in *ResolveFlagReq, opts ...grpc.CallOption) (*CommonResp, error) {
	client := admin.NewAdminClient(m.cli.Conn())
	return client.ResolveFlag(ctx, in, opts...)
}

// Audit
func (m *defaultAdmin) RecordAuditLog(ctx context.Context, in *RecordAuditLogReq, opts ...grpc.CallOption) (*CommonResp, error) {
	client := admin.NewAdminClient(m.cli.Conn())
	return client.RecordAuditLog(ctx, in, opts...)
}
