// Code generated by goctl. Safe to edit.
// goctl 1.9.2
// Source: admin.proto

package adminClient

import (
	"context"

	"journal/rpc/admin/admin"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CommonResp             = admin.CommonResp
	FlagItem               = admin.FlagItem
	ListFlagsReq           = admin.ListFlagsReq
	ListFlagsResp          = admin.ListFlagsResp
	ListPapersReq          = admin.ListPapersReq
	ListPapersResp         = admin.ListPapersResp
	ListUsersReq           = admin.ListUsersReq
	ListUsersResp          = admin.ListUsersResp
	PaperItem              = admin.PaperItem
	RecordAuditLogReq      = admin.RecordAuditLogReq
	ResolveFlagReq         = admin.ResolveFlagReq
	UpdatePaperStatusReq   = admin.UpdatePaperStatusReq
	UpdatePaperZoneReq     = admin.UpdatePaperZoneReq
	UpdateUserRoleReq      = admin.UpdateUserRoleReq
	UpdateUserStatusReq    = admin.UpdateUserStatusReq
	UserItem               = admin.UserItem
	RoleItem               = admin.RoleItem
	ListRolesReq           = admin.ListRolesReq
	ListRolesResp          = admin.ListRolesResp
	CreateRoleReq          = admin.CreateRoleReq
	CreateRoleResp         = admin.CreateRoleResp
	UpdateRoleReq          = admin.UpdateRoleReq
	DeleteRoleReq          = admin.DeleteRoleReq
	PermissionItem         = admin.PermissionItem
	ListPermissionsReq     = admin.ListPermissionsReq
	ListPermissionsResp    = admin.ListPermissionsResp
	GetRolePermissionsReq  = admin.GetRolePermissionsReq
	GetRolePermissionsResp = admin.GetRolePermissionsResp
	SetRolePermissionsReq  = admin.SetRolePermissionsReq
	ListUserRolesReq       = admin.ListUserRolesReq
	ListUserRolesResp      = admin.ListUserRolesResp
	AssignUserRoleReq      = admin.AssignUserRoleReq
	RevokeUserRoleReq      = admin.RevokeUserRoleReq
	AuditLogItem           = admin.AuditLogItem
	ListAuditLogsReq       = admin.ListAuditLogsReq
	ListAuditLogsResp      = admin.ListAuditLogsResp

	Admin interface {
		// User
		ListUsers(ctx context.Context, in *ListUsersReq, opts ...grpc.CallOption) (*ListUsersResp, error)
		UpdateUserRole(ctx context.Context, in *UpdateUserRoleReq, opts ...grpc.CallOption) (*CommonResp, error)
		UpdateUserStatus(ctx context.Context, in *UpdateUserStatusReq, opts ...grpc.CallOption) (*CommonResp, error)
		// Paper
		ListPapers(ctx context.Context, in *ListPapersReq, opts ...grpc.CallOption) (*ListPapersResp, error)
		UpdatePaperStatus(ctx context.Context, in *UpdatePaperStatusReq, opts ...grpc.CallOption) (*CommonResp, error)
		UpdatePaperZone(ctx context.Context, in *UpdatePaperZoneReq, opts ...grpc.CallOption) (*CommonResp, error)
		// Flag
		ListFlags(ctx context.Context, in *ListFlagsReq, opts ...grpc.CallOption) (*ListFlagsResp, error)
		ResolveFlag(ctx context.Context, in *ResolveFlagReq, opts ...grpc.CallOption) (*CommonResp, error)
		// Audit
		RecordAuditLog(ctx context.Context, in *RecordAuditLogReq, opts ...grpc.CallOption) (*CommonResp, error)
		ListAuditLogs(ctx context.Context, in *ListAuditLogsReq, opts ...grpc.CallOption) (*ListAuditLogsResp, error)
		// RBAC - Role
		ListRoles(ctx context.Context, in *ListRolesReq, opts ...grpc.CallOption) (*ListRolesResp, error)
		CreateRole(ctx context.Context, in *CreateRoleReq, opts ...grpc.CallOption) (*CreateRoleResp, error)
		UpdateRole(ctx context.Context, in *UpdateRoleReq, opts ...grpc.CallOption) (*CommonResp, error)
		DeleteRole(ctx context.Context, in *DeleteRoleReq, opts ...grpc.CallOption) (*CommonResp, error)
		// RBAC - Permission
		ListPermissions(ctx context.Context, in *ListPermissionsReq, opts ...grpc.CallOption) (*ListPermissionsResp, error)
		// RBAC - Role-Permission
		GetRolePermissions(ctx context.Context, in *GetRolePermissionsReq, opts ...grpc.CallOption) (*GetRolePermissionsResp, error)
		SetRolePermissions(ctx context.Context, in *SetRolePermissionsReq, opts ...grpc.CallOption) (*CommonResp, error)
		// RBAC - User-Role
		ListUserRoles(ctx context.Context, in *ListUserRolesReq, opts ...grpc.CallOption) (*ListUserRolesResp, error)
		AssignUserRole(ctx context.Context, in *AssignUserRoleReq, opts ...grpc.CallOption) (*CommonResp, error)
		RevokeUserRole(ctx context.Context, in *RevokeUserRoleReq, opts ...grpc.CallOption) (*CommonResp, error)
	}

	defaultAdmin struct {
		cli zrpc.Client
	}
)

func NewAdmin(cli zrpc.Client) Admin {
	return &defaultAdmin{
		cli: cli,
	}
}

// User
func (m *defaultAdmin) ListUsers(ctx context.Context, in *ListUsersReq, opts ...grpc.CallOption) (*ListUsersResp, error) {
	client := admin.NewAdminClient(m.cli.Conn())
	return client.ListUsers(ctx, in, opts...)
}

func (m *defaultAdmin) UpdateUserRole(ctx context.Context, in *UpdateUserRoleReq, opts ...grpc.CallOption) (*CommonResp, error) {
	client := admin.NewAdminClient(m.cli.Conn())
	return client.UpdateUserRole(ctx, in, opts...)
}

func (m *defaultAdmin) UpdateUserStatus(ctx context.Context, in *UpdateUserStatusReq, opts ...grpc.CallOption) (*CommonResp, error) {
	client := admin.NewAdminClient(m.cli.Conn())
	return client.UpdateUserStatus(ctx, in, opts...)
}

// Paper
func (m *defaultAdmin) ListPapers(ctx context.Context, in *ListPapersReq, opts ...grpc.CallOption) (*ListPapersResp, error) {
	client := admin.NewAdminClient(m.cli.Conn())
	return client.ListPapers(ctx, in, opts...)
}

func (m *defaultAdmin) UpdatePaperStatus(ctx context.Context, in *UpdatePaperStatusReq, opts ...grpc.CallOption) (*CommonResp, error) {
	client := admin.NewAdminClient(m.cli.Conn())
	return client.UpdatePaperStatus(ctx, in, opts...)
}

func (m *defaultAdmin) UpdatePaperZone(ctx context.Context, in *UpdatePaperZoneReq, opts ...grpc.CallOption) (*CommonResp, error) {
	client := admin.NewAdminClient(m.cli.Conn())
	return client.UpdatePaperZone(ctx, in, opts...)
}

// Flag
func (m *defaultAdmin) ListFlags(ctx context.Context, in *ListFlagsReq, opts ...grpc.CallOption) (*ListFlagsResp, error) {
	client := admin.NewAdminClient(m.cli.Conn())
	return client.ListFlags(ctx, in, opts...)
}

func (m *defaultAdmin) ResolveFlag(ctx context.Context, in *ResolveFlagReq, opts ...grpc.CallOption) (*CommonResp, error) {
	client := admin.NewAdminClient(m.cli.Conn())
	return client.ResolveFlag(ctx, in, opts...)
}

// Audit
func (m *defaultAdmin) RecordAuditLog(ctx context.Context, in *RecordAuditLogReq, opts ...grpc.CallOption) (*CommonResp, error) {
	client := admin.NewAdminClient(m.cli.Conn())
	return client.RecordAuditLog(ctx, in, opts...)
}

func (m *defaultAdmin) ListAuditLogs(ctx context.Context, in *ListAuditLogsReq, opts ...grpc.CallOption) (*ListAuditLogsResp, error) {
	client := admin.NewAdminClient(m.cli.Conn())
	return client.ListAuditLogs(ctx, in, opts...)
}

// RBAC - Role
func (m *defaultAdmin) ListRoles(ctx context.Context, in *ListRolesReq, opts ...grpc.CallOption) (*ListRolesResp, error) {
	client := admin.NewAdminClient(m.cli.Conn())
	return client.ListRoles(ctx, in, opts...)
}

func (m *defaultAdmin) CreateRole(ctx context.Context, in *CreateRoleReq, opts ...grpc.CallOption) (*CreateRoleResp, error) {
	client := admin.NewAdminClient(m.cli.Conn())
	return client.CreateRole(ctx, in, opts...)
}

func (m *defaultAdmin) UpdateRole(ctx context.Context, in *UpdateRoleReq, opts ...grpc.CallOption) (*CommonResp, error) {
	client := admin.NewAdminClient(m.cli.Conn())
	return client.UpdateRole(ctx, in, opts...)
}

func (m *defaultAdmin) DeleteRole(ctx context.Context, in *DeleteRoleReq, opts ...grpc.CallOption) (*CommonResp, error) {
	client := admin.NewAdminClient(m.cli.Conn())
	return client.DeleteRole(ctx, in, opts...)
}

// RBAC - Permission
func (m *defaultAdmin) ListPermissions(ctx context.Context, in *ListPermissionsReq, opts ...grpc.CallOption) (*ListPermissionsResp, error) {
	client := admin.NewAdminClient(m.cli.Conn())
	return client.ListPermissions(ctx, in, opts...)
}

// RBAC - Role-Permission
func (m *defaultAdmin) GetRolePermissions(ctx context.Context, in *GetRolePermissionsReq, opts ...grpc.CallOption) (*GetRolePermissionsResp, error) {
	client := admin.NewAdminClient(m.cli.Conn())
	return client.GetRolePermissions(ctx, in, opts...)
}

func (m *defaultAdmin) SetRolePermissions(ctx context.Context, in *SetRolePermissionsReq, opts ...grpc.CallOption) (*CommonResp, error) {
	client := admin.NewAdminClient(m.cli.Conn())
	return client.SetRolePermissions(ctx, in, opts...)
}

// RBAC - User-Role
func (m *defaultAdmin) ListUserRoles(ctx context.Context, in *ListUserRolesReq, opts ...grpc.CallOption) (*ListUserRolesResp, error) {
	client := admin.NewAdminClient(m.cli.Conn())
	return client.ListUserRoles(ctx, in, opts...)
}

func (m *defaultAdmin) AssignUserRole(ctx context.Context, in *AssignUserRoleReq, opts ...grpc.CallOption) (*CommonResp, error) {
	client := admin.NewAdminClient(m.cli.Conn())
	return client.AssignUserRole(ctx, in, opts...)
}

func (m *defaultAdmin) RevokeUserRole(ctx context.Context, in *RevokeUserRoleReq, opts ...grpc.CallOption) (*CommonResp, error) {
	client := admin.NewAdminClient(m.cli.Conn())
	return client.RevokeUserRole(ctx, in, opts...)
}
