apiVersion: v1
kind: Secret
metadata:
  name: journal-secrets
  namespace: journal
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "banishmentB022."
  MYSQL_DATABASE: "journal_biz"
  MYSQL_USER: "journal"
  MYSQL_PASSWORD: "banishmentB022."
  REDIS_PASSWORD: "banishmentB022."
  JWT_SECRET: "journal-jwt-secret-key-2026"
