// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	auth "journal/admin-api/internal/handler/auth"
	manage "journal/admin-api/internal/handler/manage"
	"journal/admin-api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: auth.AdminLoginHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/admin"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/audit-logs",
				Handler: manage.AdminListAuditLogsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/flags",
				Handler: manage.AdminListFlagsHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/flags/:id/resolve",
				Handler: manage.AdminResolveFlagHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/keyword-rules",
				Handler: manage.AdminListKeywordRulesHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/keyword-rules",
				Handler: manage.AdminCreateKeywordRuleHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/keyword-rules/:id",
				Handler: manage.AdminDeleteKeywordRuleHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/me/permissions",
				Handler: manage.AdminMyPermissionsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/news",
				Handler: manage.AdminCreateNewsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/papers",
				Handler: manage.AdminListPapersHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/papers/:id/status",
				Handler: manage.AdminUpdatePaperStatusHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/papers/:id/zone",
				Handler: manage.AdminUpdateZoneHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/permissions",
				Handler: manage.AdminListPermissionsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/roles",
				Handler: manage.AdminListRolesHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/roles",
				Handler: manage.AdminCreateRoleHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/roles/:id",
				Handler: manage.AdminUpdateRoleHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/roles/:id",
				Handler: manage.AdminDeleteRoleHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/roles/:id/permissions",
				Handler: manage.AdminGetRolePermissionsHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/roles/:id/permissions",
				Handler: manage.AdminSetRolePermissionsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/users",
				Handler: manage.AdminListUsersHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/users/:id/role",
				Handler: manage.AdminUpdateUserRoleHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/users/:id/roles",
				Handler: manage.AdminListUserRolesHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/users/:id/roles",
				Handler: manage.AdminAssignUserRoleHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/users/:id/roles/:roleId",
				Handler: manage.AdminRevokeUserRoleHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/users/:id/status",
				Handler: manage.AdminUpdateUserStatusHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1/admin"),
	)
}
