name: Copy Redis Image
on: workflow_dispatch

permissions:
  contents: read
  packages: write

jobs:
  copy-image:
    runs-on: ubuntu-latest
    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Pull and Push
        run: |
          IMAGES=(
            "docker.io/rancher/klipper-helm:v0.9.14-build20260210"
            "docker.io/rancher/local-path-provisioner:v0.0.34"
            "docker.io/rancher/mirrored-coredns-coredns:1.14.1"
            "docker.io/rancher/mirrored-metrics-server:v0.8.1"
            "docker.io/rancher/mirrored-pause:3.6"
          )
          for src in "${IMAGES[@]}"; do
            dst="ghcr.io/b022mc/${src#docker.io/}"
            docker pull $src || true
            docker tag $src $dst || true
            docker push $dst || true
          done
